Add PATH_INFO CGI variable to nginx config.
ddev/ddev pull request #4001
Opened 2022-07-15 13:35 UTC by longwave

## The Problem/Issue/Bug:

When using SimpleSAMLphp inside a ddev project with nginx, it crashes because it cannot find the `$_SERVER['PATH_INFO']` variable, which is expected to be set. This is documented at https://simplesamlphp.org/docs/1.17/simplesamlphp-install#configuring-nginx

## How this PR Solves The Problem:

The `PATH_INFO` variable will be passed from nginx to PHP.

This should have no side effects on other platforms as they don't use the `PATH_INFO` variable

## Manual Testing Instructions:

Check `phpinfo();` after applying the fix to see that `$_SERVER['PATH_INFO']` is present and correct in the PHP Variables section

(or set up SimpleSAMLphp inside a ddev project, but that is non trivial)

## Automated Testing Overview:

## Related Issue Link(s):

#3854

## Release/Deployment notes:

<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4001"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

2022-07-15 17:13 UTC, rfay requested changes
This looks innocuous, but the tests don't reflect what it did at all, because this is the default nginx in the upstream container. The place it should really be changed is in https://github.com/drud/ddev/blob/master/pkg/ddevapp/webserver_config_assets/nginx-site-drupal9.conf and all the siblings in that directory.

Note that you can change this in any project in the .ddev/nginx-full directory with the instructions given there, I'm sure you know that already. But the place for this change is in the actual configs that gets used, not in the container. (But it's fine to change it here as well.) But what we want is all the things in https://github.com/drud/ddev/blob/master/pkg/ddevapp/webserver_config_assets

2022-07-19 15:49 UTC, longwave commented
Ah OK, will push some fixes for that soon. I work around this at present by changing `.ddev/nginx-full` but it would be helpful if I didn't have to ship an nginx config at all, as we use SimpleSAMLphp on more than one project.

2022-08-13 19:51 UTC, rfay commented
Closing this for now, happy to return to it and reopen when you get some time to put into it. Should be easy.

2022-08-13 19:51 UTC, closed without merging

2026-09-21 03:35 UTC, rfay commented
If you're still interested in this after all these years @longwave 

* https://github.com/ddev/ddev/pull/8844