WIP: Add global router_http(s)_port config.
ddev/ddev pull request #4640
Opened 2023-02-10 21:24 UTC by miromichalicka

## The Issue

#3240

## How This PR Solves The Issue

## Manual Testing Instructions

## Automated Testing Overview

## Related Issue Link(s)

## Release/Deployment Notes

2023-02-10 21:25 UTC, miromichalicka commented
Next steps:
- add/fix tests
- add validation of ports
- update docs

2023-03-16 15:02 UTC, rfay commented
What do you think @miromichalicka , does this have a future?

2023-04-06 17:14 UTC, rfay requested changes
Thanks for this! It looks like it's on the right track.

* The config value in global should be same as in project, `router_http_port` and `router_https_port`
* It doesn't have support for the global command yet, `ddev config global --router-http-port=8080 --router-https-port=8443`
* I like that the project config overrides the global; that's the way it should be.
* The comments in global_config.yaml should explain the usage as they do for all the other things.
* Right now this isn't functional (please manually test) because router_http_port and router_https_port are always populated in the project .ddev/config.yaml, so those defaults always override. You'll want those to be empty I think by default.
* But it doesn't work correctly even if I remove the project-level configs of router_http_port, etc.

Please make sure to manually test, thanks!

2023-04-06 18:19 UTC, rfay commented on pkg/globalconfig/global_config.go
> +	RouterHTTPPort               string                  `yaml:"router_http_port"`
This should go *above* the project_info member, otherwise they're hidden below that.

2023-04-17 21:58 UTC, rfay commented
Rebased. Looking forward to this.

2023-05-22 20:30 UTC, miromichalicka commented
I did some manual testing and now I'm able to set up global ports with `ddev config global` command. After manually removing values from project config, I have project running on global values. I'll probably continue tomorrow with more testing. Some things ae not clear to me:

> The config value in global should be same as in project, router_http_port and router_https_port
- do you mean this https://github.com/ddev/ddev/pull/4640/files#diff-42da3ac5f97f8c2d00f51c6afe831dadaf9245cc93f258cee0e6f1a6ac2e7a06R65? Because it seems the same to me as https://github.com/ddev/ddev/pull/4640/files#diff-de9be5de8b21f6465a7e0df5c9c2f44638c0a67659ccf812cd043bfee94aeeb1R85

> It doesn't have support for the global command yet, ddev config global --router-http-port=8080 --router-https-port=8443
- I used the same flags as in the project, so the correct command should be `ddev config global --http-port=8080 --https-port=8443`. Should I change that?

> router_http_port and router_https_port are always populated in the project .ddev/config.yaml, so those defaults always override. You'll want those to be empty I think by default.
- I'm not sure I want to touch existing configs. I'll check how to modify this behaviour for new projects. Maybe that's already done with recent changes.

2023-05-22 20:47 UTC, miromichalicka commented
> I think it should be the same, router-http-port and router-https-port

 `router_http_port` and `router_https_port` are used in YAML. In CLI it seems to be http-port and https-port - https://github.com/ddev/ddev/blob/master/cmd/ddev/cmd/config.go#L244-L245, or do you have something else in mind?

> I think if we change the defaults for the project-level values to be ,omitempty in

I already have that, I'll test a new project creation tomorrow.

2023-05-22 20:49 UTC, rfay commented
Wow, let's make them the same as the yaml. Maybe keep aliases in the project config so as to not break existing?

2023-05-29 11:19 UTC, rfay commented
Yay! I'm out for a couple of weeks but look forward to getting this in.

2023-06-13 23:07 UTC, mattstein approved these changes

2023-06-14 22:29 UTC, rfay approved these changes
I think this is good now, thanks for pioneering it @miromichalicka ! Please take a look at my recent commits and the overall state and see if you like it.

2023-06-15 20:12 UTC, rfay commented
I tested all the things. 

1. If people have existing projects, the defaults are there in the .ddev/config.yaml, and will override the global values. That will likely result in some confusion.
2. `ddev config --router-http-port=""` doesn't overwrite :(

2023-06-15 20:13 UTC, merged

2023-06-15 20:42 UTC, hanoii commented
Awesome!!