Add file as alias for "src" flag (fixes #4593)
ddev/ddev pull request #4647
Opened 2023-02-13 20:54 UTC by miromichalicka

## The Issue
https://github.com/drud/ddev/issues/4593

## How This PR Solves The Issue
It's using https://github.com/spf13/pflag#mutating-or-normalizing-flag-names approach to set alias for existing flag.

## Manual Testing Instructions

## Automated Testing Overview

## Related Issue Link(s)

## Release/Deployment Notes

2023-02-19 15:57 UTC, rfay commented
On holiday/vacation but will review as soon as I have the spare brainpower :)

2023-02-24 01:27 UTC, rfay requested changes
I'd say as it stands it's not good enough, because you didn't add an alias, you replaced "src", with "file"; we don't want to *change* things, just add an alias right? 

```
rfay@rfay-tag1-m1:~/workspace/d9$ ddev import-db -h
Import a sql file into the project.
The database dump file can be provided as a SQL dump in a .sql, .sql.gz, sql.bz2, sql.xz, .mysql, .mysql.gz, .zip, .tgz, or .tar.gz
format. For the zip and tar formats, the path to a .sql file within the archive
can be provided if it is not located at the top level of the archive. An optional target database
can also be provided; the default is the default database named "db".
Also note the related "ddev mysql" command

Usage:
  ddev import-db [project] [flags]

Examples:
ddev import-db
ddev import-db --src=.tarballs/junk.sql
ddev import-db --src=.tarballs/junk.sql.gz
ddev import-db --target-db=newdb --src=.tarballs/db.sql.gz
ddev import-db --src=.tarballs/db.sql.bz2
ddev import-db --src=.tarballs/db.sql.xz
ddev import-db <db.sql
ddev import-db someproject <db.sql
gzip -dc db.sql.gz | ddev import-db

Flags:
      --extract-path string   If provided asset is an archive, provide the path to extract within the archive.
  -f, --file string           Provide the path to a sql dump in .sql or tar/tar.gz/tgz/zip format
  -h, --help                  help for import-db
      --no-drop               Set if you do NOT want to drop the db before importing
  -p, --progress              Display a progress bar during import (default true)
  -d, --target-db string      If provided, target-db is alternate database to import into (default "db")

Global Flags:
  -j, --json-output   If true, user-oriented output will be in JSON format.
```

2023-02-24 15:06 UTC, miromichalicka commented
I pushed a change which will keep the original flags there. However, I wasn't able to figure out so far, how to print aliases in the help message.
The other solution would be to add also alias as a standalone flag. That way it would get printed out. However, I'm not sure how it would behave if you fill both flags and they try to access the same variable.
If you have any other suggestions, I'm happy to check them.

2023-02-24 15:19 UTC, rfay commented
I don't mind trying a duplicate flag; the help can just say "alias for --src" and what it does? Thanks for your work on this!

2023-02-25 15:48 UTC, rfay requested changes
This is looking fine to me; manually tested, it's great. But I think there should be a hint in a couple of places about the `--file` alias. 
1. Add an example that has it in each of them
2. Add to the `--src` description "--file can be used an alias of --src" ?

2023-02-25 15:50 UTC, rfay commented
BTW, if you'll PM me your email address I'll add you to the buildkite team so you can restart buildkite tests, etc.

2023-03-27 06:55 UTC, miromichalicka commented
Planning to have a look during this weekend, been sick for the past two weeks.

2023-04-06 17:15 UTC, rfay commented
When you're well, please update the requested item and hopefully I'll have some time for regular maintenance now. Thanks!

2023-06-14 19:18 UTC, rfay commented
What do you think about the simpler approach of just adding a new flag that does the exact same thing? Its description could be "same as --src" for example?

So you'd just add 

```
	ImportDBCmd.Flags().StringVarP(&dbSource, "file", "", "", "Provide the path to a sql dump in .sql or tar/tar.gz/tgz/zip format (same as --src)")
```

2023-06-23 20:40 UTC, rfay commented
Closing in favor of 
* #5013
We'll try to get you commit credit on that one.

2023-06-23 20:40 UTC, closed without merging