improve tableplus connection view
ddev/ddev pull request #4692
Opened 2023-03-02 14:58 UTC by riconeitzel

with latest tableplus version a connection label and color will be shown prominently in the header bar. By default it is gray and shows "PRODUCTION" for these ddev connections.

This change labels them as "DDEV" and sets the color to ddev's key color so you don't get confused whether it's a PROD connection or a DDEV connection.

See example: https://r.b71a.de/Igz6FHB7.png

Reference: https://twitter.com/TablePlus/status/1631300835530665985?s=20

2023-03-02 17:42 UTC, rfay commented
Thanks!

2023-03-04 01:32 UTC, rfay requested changes
I'm glad this works for you, but maybe it doesn't work in the trial version?

<img width="1427" alt="image" src="https://user-images.githubusercontent.com/112444/222868382-1df2f77a-0231-41ca-bc8e-f50474c2e043.png">

It think it may be worth considering removal of the `set -x` at this point too? But it's pretty useful right now for studying this.

<img width="353" alt="image" src="https://user-images.githubusercontent.com/112444/222868521-a6fe8ff4-f10b-4d43-8e61-2728cc504516.png">

2023-03-16 15:01 UTC, rfay commented
I hope you'll be able to respond and check this out and we can get this in.

2023-03-18 00:28 UTC, riconeitzel commented
hey @rfay … can you quickly address how I can assist? Removal of set -x seems fine if we don't want the output. I don't care much so … fine to remove. However I cannot test the trial version, but I'm happy to shoot out a message to their dev team. They seemed to be quite fast responding to these issues. I'll keep you posted.

2023-03-18 00:51 UTC, riconeitzel commented
https://twitter.com/tableplus/status/1636890112410947589?s=46&t=IEaWKOHqOHo--eDWO8NnJg

So you’re using the current stable, I’m using the beta. We can keep this ticket open, till the next version is released, then it works for everyone.

rico

2023-03-18 00:54 UTC, rfay commented
Thanks for checking. Just say the word and we'll reopen this when its' released. You can just comment here. Thanks for your work on this!

We will want to make sure that this doesn't break people who have older versions.

2023-03-18 00:54 UTC, closed without merging

2023-03-18 01:00 UTC, huyphams commented
Hi guys, I just wanna confirm that it will work for all. The reasons it does not work for the current version are:
1. There is a typo in the current version, we use enviroment instead of environment. We fixed it in the next update, also alias it to tag/env (you can use any of these params). So please use the correct params: env or tag 

2. The user who created this PR us the hotpatch, not the beta. Which fixed the issue.

2023-03-18 01:01 UTC, huyphams commented
You can download the hot patch release here: https://www.dropbox.com/s/3rbnoo74s03ekam/TablePlus.dmg?dl=0

2023-03-18 09:59 UTC, riconeitzel commented
I'm just amazed that @huyphams from tableplus follows the tweets to the pull request and takes the time to help! 🚀 😍