[DOCS] Update credStore to Colima to avoid ddev start errors
ddev/ddev pull request #4790
Opened 2023-03-29 23:33 UTC by chri5tia

## The Issue
When switching from Docker Desktop and installing colima and docker via homebrew, following the documentation. I ran into the following issue when running `ddev start` on my project.

```
', stderr='failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: rpc error: code = Unknown desc = error getting credentials - err: docker-credential-desktop resolves to executable in current directory (./docker-credential-desktop), out: ``' 
```

DDev was still looking for a docker desktop file, despite it being fully uninstalled.

## How This PR Solves The Issue
This PR updates documentation to provide a configuration tip when migrating from Docker Desktop to Colima. 
The `.docker/config.json` should to be updated to:

```
{
        "auths": {},
        "credStore": "colima",
        "currentContext": "colima"
}
```

## Manual Testing Instructions
PR does not change code; testing should follow the steps added to documentation for installation.

## Automated Testing Overview

## Related Issue Link(s)
https://stackoverflow.com/questions/67642620/docker-credential-desktop-not-installed-or-not-available-in-path#comment132716686_68202428

## Release/Deployment Notes

2023-03-30 01:22 UTC, rfay requested changes
It's easier to just delete ~/.docker. What do you think about that?

2023-03-30 01:22 UTC, rfay commented
I'm glad you brought this up!

2023-03-30 14:26 UTC, chri5tia commented
> It's easier to just delete ~/.docker. What do you think about that?

I had completely uninstalled and removed docker desktop. It's possible that this directory was still on the system. Since I ran into this after installing docker with brew as part of setting it up with Colima it would be too late at that point to delete the the whole directory, wouldn't it? I assume it was a default value which wasn't set during the Colima set up process. Not sure where to go from here.

2023-03-30 14:40 UTC, rfay commented
Yeah, Docker Desktop doesn't remove lots of things, and ~/.docker is one of them. 

I have never heard of anybody needing the contents of ~/.docker when switching away from Docker Desktop. 

Note that it's not necessary to uninstall Docker Desktop to use colima, and the docker client provided with Docker Desktop works fine with colima.

So I think it would be useful to suggest removing ~/.docker/config.json if uninstalling Docker Desktop.

2023-03-30 20:32 UTC, rfay commented
The suggestion in Stack Overflow isn't even correct; you can't just change to ` "credsStore": "colima",`, there isn't a credStore AFAIK, and the name would be the name of a profile. 

I would recommend 1) Removing docker.json in case of trouble or 2) Remove the credsStore line.  Why don't we just update this PR to say "Remove the credsStore line".

2023-03-30 20:47 UTC, mattstein commented
> I would recommend 1) Removing docker.json in case of trouble or 2) Remove the credsStore line. Why don't we just update this PR to say "Remove the credsStore line".

Sounds more specific and accurate, so great AFAIK!

2023-04-06 18:10 UTC, rfay commented
Made the suggested changes.

2023-04-06 21:57 UTC, mattstein requested changes

2023-04-06 21:57 UTC, mattstein commented on docs/content/users/install/docker-installation.md
> +    !!!tip "Docker Desktop may have left a bad config.json"
Wrap filename in backticks:

```suggestion
    !!!tip "Docker Desktop may have left a bad `config.json`"
```

2023-04-06 21:57 UTC, mattstein commented on docs/content/users/install/docker-installation.md
> +        Remove the `credsStore` line in `~/.docker/config.json` if you have trouble.
Qualify what kind of trouble makes this relevant so it’s less broad and open-ended:

```suggestion
        Remove the `credsStore` line in `~/.docker/config.json` if you have trouble running `ddev start` with a project you’ve migrated.
```

2023-04-06 21:57 UTC, mattstein commented on docs/content/users/install/docker-installation.md
> +    2. Remove the `credsStore` line.
I’m not sure why these steps repeat the exact same instruction in a numbered list format outside the admonition, so it seems best to remove them:

```suggestion
```

2023-04-06 22:14 UTC, merged