[docs] Fix markdown in profiling doc page
ddev/ddev pull request #4806
Opened 2023-04-05 16:59 UTC by oleksii-lisovyi

## The Issue
Here's how steps numbers section looks a bit broken:
<img width="786" alt="Screenshot 2023-04-05 at 19 47 25" src="https://user-images.githubusercontent.com/3918875/230151324-32abbf91-c02b-4a03-8a54-a34465f7dffd.png">

## How This PR Solves The Issue
Well, it looks now as initended.

2023-04-05 17:08 UTC, mattstein requested changes
Thank you for this, @oleksii-lisovyi! It was definitely mangled and you definitely fixed it.

Would you mind adding two spaces to fully indent that “You can also (...)” sentence with its parent list item?

![Screen Shot 2023-04-05 at 10 06 14 AM@2x](https://user-images.githubusercontent.com/2488775/230153491-5ab49ac4-513a-4d44-8edd-8b4a1f5aeeca.png)

I left that as a code suggestion you can commit using **Commit suggestion**.

2023-04-05 17:08 UTC, mattstein commented on docs/content/users/debugging-profiling/blackfire-profiling.md
>    You can also do this with `ddev config global --web-environment-add="BLACKFIRE_SERVER_ID=<id>,BLACKFIRE_SERVER_TOKEN=<token>,BLACKFIRE_CLIENT_ID=<id>,BLACKFIRE_CLIENT_TOKEN=<token>"`, but any exist
```suggestion
    You can also do this with `ddev config global --web-environment-add="BLACKFIRE_SERVER_ID=<id>,BLACKFIRE_SERVER_TOKEN=<token>,BLACKFIRE_CLIENT_ID=<id>,BLACKFIRE_CLIENT_TOKEN=<token>"`, but any existing environment variables will be deleted.
```

2023-04-05 18:24 UTC, rfay commented
Thanks @oleksii-lisovyi - Could you also say something about your blackfire usage? I was wondering if anybody used it any more since the free/hacker plan went away. I assume you use Platform.sh?

2023-04-05 19:22 UTC, oleksii-lisovyi commented
@rfay honestly just started exploring this in depth. haven't had any decent experience to be able to comment on that.
so far trying to make it work, tho there are some limitations with license I wasn't yet able to overcome.

2023-04-05 20:23 UTC, rfay commented
Yeah, I don't think you can use it at all any more without a paid account.

2023-04-06 00:12 UTC, tyler36 commented
From Blackfire [pricing page](https://www.blackfire.io/pricing/#free-trial):

> We don't provide a free trial. 

If it's paid-only, perhaps it should be extracted to an addon and removed from DDEV?

2023-04-06 00:50 UTC, rfay commented
Right, there is no free trial, but I'm interested if people have a subscription and are still using it any more. Blackfire is a product of Platform.sh, a major sponsor of DDEV, but no matter how much I pester, I can't get them to bring back the hacker/localdev/free account.

Moving it to an add-on seems possible.

2023-04-06 16:44 UTC, merged