Add debugging output to GetHostDockerInternalIP() for #4803
ddev/ddev pull request #4813
Opened 2023-04-14 16:15 UTC by rfay

## The Issue

* #4803 
* https://github.com/ddev/ddev/issues/3772#issuecomment-1505090962

## How This PR Solves The Issue

Capture information on how host.docker.internal is generated; To see where it comes from, `export DDEV_DEBUG=true` and then `ddev start`

2023-04-14 20:53 UTC, mattstein requested changes

2023-04-14 20:53 UTC, mattstein commented on docs/content/users/debugging-profiling/step-debugging.md
> +* Delete existing PhpStorm "servers" in settings, or recreate the vscode launch.json exactly as shown in the instructions here.
Product name + backticks for filename: 

```suggestion
* Delete existing PhpStorm "servers" in settings, or recreate the VS Code’s `launch.json` file exactly as shown in the instructions here.
```

2023-04-14 20:53 UTC, mattstein commented on docs/content/users/debugging-profiling/step-debugging.md
> +* Use `curl` or a browser to create a web request. For example, `curl https://d9.ddev.site` or just `ddev exec curl localhost`.
Run commands and avoid “just”: 

```suggestion
* Use `curl` or a browser to create a web request. For example, `curl https://d9.ddev.site` or run `ddev exec curl localhost`.
```

2023-04-14 20:53 UTC, mattstein commented on docs/content/users/debugging-profiling/step-debugging.md
> +* You can `export DDEV_DEBUG=true` and `ddev start` to get information about how `host.docker.internal` is figured out; this can help in some situations, especially with WSL2. (`host.docker.internal`
Run commands:

```suggestion
* You can run `export DDEV_DEBUG=true` and `ddev start` to get information about how `host.docker.internal` is figured out, which can help in some situations especially with WSL2. (`host.docker.internal` inside the web container is where Xdebug thinks it should connect to your IDE. You can see what it is set to by running `ddev exec ping host.docker.internal`.)
```

2023-04-14 21:00 UTC, rfay commented on docs/content/users/debugging-profiling/step-debugging.md
> +* Delete existing PhpStorm "servers" in settings, or recreate the vscode launch.json exactly as shown in the instructions here.
```suggestion
* Delete existing PhpStorm "servers" in settings, or recreate VS Code’s `launch.json` file exactly as shown in the instructions here.
```

2023-04-14 21:01 UTC, mattstein commented on docs/content/users/debugging-profiling/step-debugging.md
> +* Delete existing PhpStorm "servers" in settings, or recreate the vscode launch.json exactly as shown in the instructions here.
Whoops, good catch!

2023-04-14 21:43 UTC, rfay commented on docs/content/users/debugging-profiling/step-debugging.md
> +* Delete existing PhpStorm "servers" in settings, or recreate the vscode launch.json exactly as shown in the instructions here.
Finally found a nit on @mattstein !

2023-04-20 15:32 UTC, ultimike commented
Tested. Output below:

```
~/sites/pmd-2023-winter/pmd 💎 export DDEV_DEBUG=true
~/sites/pmd-2023-winter/pmd 💎 ddev start
Starting pmd... 
Pulling image for drud/ddev-webserver:20230315_drush8 
Pulling image for busybox:stable 
Pulling image for drud/ddev-ssh-agent:v1.21.5 
Pulling image for drud/ddev-router:v1.21.5 
GetDockerContext: contextInfo='default unix:///Users/michael/.colima/default/docker.sock' 
Using docker context default (unix:///Users/michael/.colima/default/docker.sock) 
host.docker.internal=192.168.5.2 because running on Colima 
Pulling image for drud/ddev-dbserver-mariadb-10.4:v1.21.5 
Pulling image for drud/ddev-webserver:20230315_drush8 
Pulling image for drud/ddev-router:v1.21.5 
Pulling image for drud/ddev-ssh-agent:v1.21.5 
Executing docker-compose -f /Users/michael/sites/pmd-2023-winter/pmd/.ddev/.ddev-docker-compose-full.yaml up --build -d 
Network ddev-pmd_default  Created 
Container ddev-pmd-db  Started 
Container ddev-pmd-web  Started 
Copied /Users/michael/Library/Application Support/mkcert:CopyIntoVolume_mkrakykfydoz into /mnt/v/mkcert in 120.457167ms 
Exec chown -R 501 /mnt/v/mkcert stdout=, stderr=, err=<nil> 
Pushed mkcert rootca certs to ddev-global-cache/mkcert 
Starting mutagen sync process... This can take some time. 
chowning mutagen docker volume for user 501 
done chowning mutagen docker volume; result=<nil> 
Using mutagen config file /Users/michael/sites/pmd-2023-winter/pmd/.ddev/mutagen/mutagen.yml 
Resume mutagen sync if session already exists 
Resuming mutagen sync: mutagen [sync resume pmd] 
Flushing mutagen sync session 'pmd' 
Flushed mutagen sync session 'pmd' 
Mutagen sync flush completed in 2s.
For details on sync status 'ddev mutagen st pmd -l' 
Testing to see if /mnt/ddev_config is properly mounted 
Container ddev-router  Started 
Ensuring write permissions for pmd 
Existing settings.php file includes settings.ddev.php 
Ensuring write permissions for pmd 
Successfully started pmd 
Project can be reached at https://pmd.ddev.site https://127.0.0.1:49621 
Instrumentation is opted in, but SegmentKey is not available. This usually means you have a locally-built ddev binary or one from a PR build. It's not an error. Please report it if you're using an official release build. 
~/sites/pmd-2023-winter/pmd 💎 ddev -v
ddev version v1.21.6-44-gcb137d67
```

2023-04-26 20:16 UTC, merged