Delete FUNDING.yml
ddev/ddev pull request #4929
Opened 2023-05-18 22:23 UTC by gilbertsoft

Use FUNDING.yml from the default community health file instead (https://github.com/ddev/.github/blob/main/FUNDING.yml)

2023-05-18 22:27 UTC, rfay requested changes
Last I looked, the org one wasn't working. For example, see https://github.com/ddev/ddev-platformsh or https://github.com/ddev/ddev-addon-template - they don't have the funding info. So I don't think we can remove this.

I guess we should ask their support about it.

2023-05-18 22:30 UTC, gilbertsoft commented
> Last I looked, the org one wasn't working. For example, see https://github.com/ddev/ddev-platformsh or https://github.com/ddev/ddev-addon-template - they don't have the funding info. So I don't think we can remove this.
> 
> I guess we should ask their support about it.

Doesn't work there because sponsoring isn't enabled in these repos. Here it works fine https://github.com/ddev/localdev.foundation

2023-05-18 22:31 UTC, gilbertsoft commented
Activated for https://github.com/ddev/ddev-addon-template now and works too

2023-05-18 22:33 UTC, gilbertsoft commented
Btw fixed the second link before which wasn't a link and has broken custom links.

2023-05-19 00:49 UTC, gilbertsoft commented
Sposoring should now be active in all repos.

2023-05-19 13:01 UTC, rfay approved these changes
Thanks for sorting this out!

2023-05-19 13:01 UTC, merged