Avoid changing an already set type but show a warning
ddev/ddev pull request #5011
Opened 2023-06-22 18:36 UTC by gilbertsoft

## The Issue

#4403

## How This PR Solves The Issue

## Manual Testing Instructions

## Automated Testing Overview

## Related Issue Link(s)

## Release/Deployment Notes

2023-06-26 21:59 UTC, rfay reviewed
This seems to work as specified, but still emits the message:
`You have specified a project type of 'php' but a project of type 'drupal9' was discovered in /home/rfay/workspace/d9/web` - is that intended?

2023-06-26 22:09 UTC, rfay requested changes
Thanks for solving this problem.

It looks to me like this mostly solves the problem, except that it doesn't respect existing with `ddev config` interactive configuration.

Could we use `none` for the no-project-type option? Have a better idea?

The `ddev config --project-type` would then have to take "none", but I imagine it already would with GetAppTypes() having the listed items.

Docs will need update to explain the situation of "none"; I'm pretty sure they say "php" is the default.

Don't forget that "none" in a python or django4 project would be controlled by webserver_type and may be a bit different.

2023-06-27 06:24 UTC, gilbertsoft commented on pkg/nodeps/values.go
> +	AppTypeNone      = ""
Just an internal thing which never gets saved to the config, so value is not important here but we can change it to none if you prefer.

2023-06-27 06:32 UTC, gilbertsoft commented
> However, if you use the simple `ddev config` command, it discovers the docroot and then switches to the discovered type. That's not what you want is it?

Have to check interactive config again...

2023-06-27 06:35 UTC, gilbertsoft commented
> It looks to me like this mostly solves the problem, except that it doesn't respect existing with `ddev config` interactive configuration.

Will check again...

> Could we use `none` for the no-project-type option? Have a better idea?
> 
> The `ddev config --project-type` would then have to take "none", but I imagine it already would with GetAppTypes() having the listed items.

No, like explained above `none` is an internal value only during the init of the ddevapp and is no valid option for the user. If it's still `none` on saving it gets replaced by `php` instead.

> Docs will need update to explain the situation of "none"; I'm pretty sure they say "php" is the default.

`php` is still the default, has not changed see above.

2023-06-27 10:08 UTC, gilbertsoft commented
Interactive config works for me so far. Can you please explain your exact case a bit more @rfay ?
![grafik](https://github.com/ddev/ddev/assets/25326036/849aa61c-05f1-41ba-95f6-2e777e2e96be)

2023-06-27 13:45 UTC, gilbertsoft commented
> Here's interactive config with it changing the project type from `php` back to `drupal9`. Maybe this is intended and OK? But it's changing it back when not expected probably.

Got it now. Okay, we have to discuss the desired behavior then. At the moment the discovered project type is suggested during interactive setup. To me this looks fine but well, one could have an other opinion. I'm open for both ways...

2023-06-27 17:05 UTC, gilbertsoft commented on pkg/ddevapp/config.go
> +	validAppTypes := strings.Join(GetValidAppTypes(), ", ")
Returns a slice of the defined app types, nothing new.

2023-07-03 14:46 UTC, rfay commented
Rebased

2023-07-03 18:27 UTC, rfay approved these changes
Seems good to me, did manual testing again. Thanks!

2023-07-04 18:08 UTC, merged