Update index.md
ddev/ddev pull request #5014
Opened 2023-06-23 15:53 UTC by jmarkel

Added Rancher Desktop as a container system that Ddev works on

## The Issue
I happily use Rancher Desktop on Mac as my container-supporting environment for Ddev, but it's not currently shown in the docs
## How This PR Solves The Issue
Added Rancher Desktop to the list along with Colima and Docker Desktop
## Manual Testing Instructions
N/A
## Automated Testing Overview
N/A - Doc only

## Related Issue Link(s)
N/A
## Release/Deployment Notes
N/A - Doc only

2023-06-23 16:55 UTC, mattstein commented
Thanks @jmarkel, I’m glad it works well!

We have a [section in the docs about Rancher](https://ddev.readthedocs.io/en/stable/users/configuration/experimental/#rancher-desktop-on-macos) and I think it’s left out of this page as a matter of test coverage and support. @rfay can correct me if I’m wrong, though!

2023-06-23 17:15 UTC, rfay commented
I'm glad it's working also. We don't have testing coverage for it, so I'm reluctant to encourage it. 

Previously we had https://ddev.readthedocs.io/en/stable/users/configuration/experimental/#rancher-desktop-on-macos but I seem to have removed that due to lack of experience and test coverage. If you want to reintroduce it on the Experimental section given your experience, I'm OK with that, will hope that you'd maintain it. 

Related:
* https://github.com/ddev/ddev/issues/4858

2023-06-23 17:17 UTC, rfay requested changes
As above, OK to introduce in experimental again, if you're willing to give complete instructions and maintain the page.

2023-06-28 21:09 UTC, rfay commented
Will close this if not addressed by 3 July. It will be fine to re-open or address in other ways in the future.

2023-07-15 19:04 UTC, rfay commented
An interesting note is that Rancher Desktop runs on Windows and integrates with both traditional Windows and WSL2, similarly to Docker Desktop. 

On both WSL2 and traditional Windows we get no internet access from inside the web container.

And on traditional Windows we get a panic apparently something from go-dockerclient:
```
docker.io/ddev/ddev-dbserver-mariadb-10.4:v1.22.0-beta4
2023/07/15 13:00:57 http2: server: error reading preface from client //./pipe/docker_engine: file has already been closed
 Container ddev-junk-web  Created
 Container ddev-junk-db  Created
 Container ddev-junk-db  Started
 Container ddev-junk-web  Started
panic: interface conversion: *winio.win32Pipe is not interface { CloseWrite() error }: missing method CloseWrite

goroutine 320 [running]:
github.com/fsouza/go-dockerclient.(*Client).hijack.func1.2()
        /home/rfay/workspace/ddev/vendor/github.com/fsouza/go-dockerclient/client.go:832 +0x9e
created by github.com/fsouza/go-dockerclient.(*Client).hijack.func1
        /home/rfay/workspace/ddev/vendor/github.com/fsouza/go-dockerclient/client.go:826 +0x345
```

Oddly, `ddev version` shows "docker type" of "Docker Desktop for Windows"

```
$ ddev version
 ITEM             VALUE
 DDEV version     v1.22.0-beta3-21-g57d7804d4
 architecture     amd64
 db               ddev/ddev-dbserver-mariadb-10.4:v1.22.0-beta4
 ddev-ssh-agent   ddev/ddev-ssh-agent:v1.22.0-beta1
 docker           23.0.6
 docker type      Docker Desktop For Windows
 docker-compose   v2.20.0
 docker-platform  rfay-xps13
 mutagen          0.17.2
 os               windows
 router           traefik:v2.10
 web              ddev/ddev-webserver:20230707_fix_process_group_kill
```

2023-08-10 00:56 UTC, rfay commented
I took Rancher Desktop for a spin on macOS and it did fine.

2023-08-10 14:51 UTC, mattstein commented
The “Experimental” section reads to me like people with lab coats are actively prodding at the subjects, with the intention of folding them in as core features once weird things stop happening.

It might be more straightforward to write an FAQ item that covers the status of not-officially-supported container systems, so they’re acknowledged in the docs and offer hints for adventurous users. Doesn’t have to be a declaration of support, but sharing knowledge exactly like this and having a place to keep it up to date.

2023-08-10 16:27 UTC, mattstein commented
I think _where_ is the easy part: in the [Features & Requirements](https://ddev.readthedocs.io/en/stable/users/usage/faq/#features-requirements) section of the FAQ, under a new “What container systems will DDEV work with?” item.

I’ll draft it if you want, but I’m out of the loop so I’d need the tl;dr on options and their status. I can get the table this far:

| Container System | Support Level |
| -- | -- |
| Docker Desktop | officially tested and supported |
| Colima | officially tested and supported |
| Rancher Desktop | seems fine on macOS, but not automatically tested or officially supported |
| the other ones? | ?? |

2023-08-10 16:36 UTC, rfay commented
That would be awesome. Other ones:

OrbStack: works great on macOS but not yet officially tested and doesn't have automated tests
Rancher Desktop doesn't seem to work right on Windows WSL2

Note that there may be other classes of docs that could be handled like this, for example, installation techniques. You can install so many ways, and all of them do fine. Latest I've discovered is nix. but there's installing head, installing edge, etc.

2023-08-10 16:52 UTC, rfay commented
Each of them probably needs a bit of setup "fu". For example, on Rancher Desktop Kubernetes is enabled by default and you'd most likely want to disable it. On Orbstack there's an initial setup that IIRC comes out right but could be baffling first time. It has many capabilities besides Docker. Of course Colima can be set up a thousand ways besides how we specify. And Docker Desktop also.

2023-08-17 01:49 UTC, mattstein commented
The FAQ item could still be brief, with links off to blog posts (first- or third-party) that offer a dated glimpse of status + setup notes in lieu of the docs that’d come with official support:

```markdown
**What container systems with DDEV work with?**

We refer to a container system as being supported when we’ve established documentation and automated tests for it. If you’re comfortable navigating setup issues yourself, however, it’s likely you can get DDEV working with container systems we don’t officially support yet.

| Container System   | Support Level                                              |
| ------------------ | ---------------------------------------------------------- |
| Docker Desktop     | officially tested and supported                            |
| Colima             | officially tested and supported                            |
| Rancher Desktop    | seems fine on macOS, not supported or automatically tested |
| OrbStack           | great on macOS, not supported or automatically tested      |
```

2023-08-17 01:58 UTC, rfay commented
Thanks, That's probably reasonable. And my hesitation on Rancher and Orbstack is *not* necessarily reasonable. We support Gitpod and Codespaces without official automated testing.

2023-08-17 02:06 UTC, mattstein commented
The way I see it, @rfay, whatever “supported” means is your call! I think of Gitpod and Codespaces as different animals (right or not!), the feature here is just a format to address known container systems and convey to someone what sort of experience they might expect with them.

2023-08-23 17:55 UTC, rfay commented
@jmarkel thanks for raising this. I'm going to close this in favor of
* #5293

where I gave you commit credit. 

Would you be willing to write a short (or long) blog article on ddev.com about how you use and set up Rancher Desktop? It's just a PR to https://github.com/ddev/ddev.com-front-end explained in https://ddev.com/blog/ddev-website-for-contributors/

2023-08-23 17:55 UTC, closed without merging