gh codespaces: bump docker-in-docker to v2
ddev/ddev pull request #5061
Opened 2023-07-02 09:45 UTC by mandrasch

## The Issue

- according to https://containers.dev/features latest version of docker-in-docker is 2.2.0, ddev docs still refer to v1

## How This PR Solves The Issue

- bump to v2

## Manual Testing Instructions

- setup ddev in codespaces, check test project

Beware: `setup_test_project.sh` currently fails with

```bash
2023-07-02 09:41:48.611Z: + ddev delete -Oy tmp
2023-07-02 09:41:49.204Z: Failed to get project(s): could not find requested project 'tmp', you may need to use "ddev start" to add it to the project catalog
2023-07-02 09:41:49.297Z: postCreateCommand failed with exit code 1. Skipping any further user-provided commands.
```

I did full rebuilds, it failed on docker-in-docker v1 as well as v2.

## Automated Testing Overview

- no automated tests for codespaces so far iirc

## Related Issue Link(s)

- https://github.com/ddev/ddev/issues/5033#issuecomment-1615076600

## Release/Deployment Notes

- update docs, prs are add: https://github.com/ddev/ddev/pull/5060

2023-07-02 12:00 UTC, gilbertsoft requested changes
Thanks, looks good!

You can fix the mentioned issue in the script by changing line 10 to `ddev delete -Oy tmp >/dev/null || true`.

2023-07-03 12:57 UTC, rfay commented
We'll do a new package build for this.

2023-07-03 16:24 UTC, rfay approved these changes
This seems fine. We can push this to new package even before pulling it if we want to, makes it easy to test on Codespaces that way.

2023-07-03 18:14 UTC, gilbertsoft approved these changes

2023-07-03 20:23 UTC, merged

2023-07-03 23:21 UTC, rfay commented
@mandrasch I hope you'll take a look and see how this is working for you. All the various related PRs should be pulled, and new package has been created.