docs: point to new location of DDEV Github action
ddev/ddev pull request #5105
Opened 2023-07-07 23:45 UTC by jonaseberle

## The Issue

https://github.com/jonaseberle/github-action-setup-ddev has been migrated to https://github.com/ddev/github-action-setup-ddev.

I suggest to use the Github marketplace URL as a landing page in the docs.

2023-07-07 23:51 UTC, rfay approved these changes
Thanks!

2023-07-08 10:36 UTC, gilbertsoft requested changes

2023-07-08 10:36 UTC, gilbertsoft commented on docs/content/users/topics/remote-docker.md
> +Examples of this approach are demonstrated in [Codeception Tests in Travis CI with DDEV and Selenium](https://dev.to/tomasnorre/codeception-tests-in-travis-ci-with-ddev-and-selenium-1607) and [Setup
```suggestion
Examples of this approach are demonstrated in [Codeception Tests in Travis CI with DDEV and Selenium](https://dev.to/tomasnorre/codeception-tests-in-travis-ci-with-ddev-and-selenium-1607) and [Setup DDEV in GitHub Workflows](https://github.com/marketplace/actions/setup-ddev-in-github-workflows).
```

2023-07-08 13:03 UTC, gilbertsoft approved these changes
Fixed names, looks good now, thanks!

2023-07-10 02:07 UTC, mattstein approved these changes

2023-07-10 15:48 UTC, merged