feat: create global pip & pip3 cmds and update commands.md accordingly,  fixes #5161
ddev/ddev pull request #5162
Opened 2023-07-18 16:40 UTC by rpkoller

## The Issue
https://github.com/ddev/ddev/issues/5161

## How This PR Solves The Issue
It creates to global commands (pip & pip3) and updates the commands.md

## Manual Testing Instructions

## Automated Testing Overview

## Related Issue Link(s)

## Release/Deployment Notes

2023-07-18 19:00 UTC, rfay requested changes
I think this should probably only be available for python and django4 project types? I hate to see so many thousands of commands cluttering up `ddev -h`. 

I don't think we need both `pip` and `pip3` since `pip` in this container is `pip3` (only python3 is installed in the container by default, but python-is-python3 is installed. I can be talked out of this stance, but regardless I'd rather have just one file and a symlink? Could that be done?

2023-07-18 20:04 UTC, rpkoller commented
> I think this should probably only be available for python and django4 project types? I hate to see so many thousands of commands cluttering up ddev -h.

I also considered adding `## ProjectTypes: django4,python` to the two global commands when i created the PR. but couldnt it be the case that someone wants to use a python package for whatever reason in a php based project like drupal? making pip exclusive to django and python would make it opinionated? and the other package managers aren't project type specific either? 

> I don't think we need both pip and pip3 since pip in this container is pip3 (only python3 is installed in the container by default, but python-is-python3 is installed. I can be talked out of this stance, but regardless I'd rather have just one file and a symlink? Could that be done?

oh i never version checked python and python3 with `python --version`. i am not sure then. i would rather tend to remove the global command for `pip` and just keep `pip3` since there is only `python3` available in the web container. keeping `pip` would be wrong and would create false expectations. would it even be possible to remove the `python` command in the web container a well, since there is no python2 available? and the python global command could be renamed to python3 ? 
and in addition also communicate in the docs that python 3 is installed and python2 not available? but by only providing the commands `python3` and `pip3` it should be probably clear enough for regular python users but still having it noted in the docs as well would make sense from my point of view?

2023-07-18 21:36 UTC, mattstein approved these changes
Looks good to me! We use the phrase “(global shell web container command)” all over this page without clarifying what that means, but that’s not a problem here since this PR is following suit.

2023-07-19 15:04 UTC, rfay commented
I'm sure this will land, but after v1.22.0. Thanks for the initiative!

2023-07-25 10:26 UTC, tbal commented on docs/content/users/usage/commands.md
> +pip3 pip3 install --upgrade
this should probably be more like, right?
```suggestion
ddev pip3 install --upgrade
```

2023-08-10 00:27 UTC, rfay commented
Thanks so much for this contribution, but I don't think we need these wrappers at this time. I think people are better to be using `ddev exec` at this point.

2023-08-10 00:27 UTC, closed without merging