add zstd support
ddev/ddev pull request #5244
Opened 2023-08-07 14:13 UTC by kringkaste

## The Issue

Missing support for Zstandard (zstd) compression.

## How This PR Solves The Issue

Add support for Zstandard compression.

## Manual Testing Instructions

e.g. `ddev import-db --file=archive.sql.zst`

## Automated Testing Overview

Added the new compression format to the existing tests of various other compression formats.

## Release/Deployment Notes

None.

<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5244"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

2023-08-07 14:43 UTC, rfay reviewed
I guess I thought the file extension was `ztsd` not `zts` ?

2023-08-07 14:43 UTC, rfay commented on pkg/ddevapp/ddevapp_test.go
> +			extensions := []string{"tgz", "zip", "tar.xz", "tar.bz2", "tar.zst", "tar.gz"}
`tar. zst` isn't going to work is it?

2023-08-07 14:57 UTC, rfay commented
https://en.wikipedia.org/wiki/Zstd says it's .zts :)

2023-08-07 14:58 UTC, rfay commented
It looks like you didn't do `go mod tidy`, please follow up with that.

2023-08-07 14:58 UTC, kringkaste commented
> https://en.wikipedia.org/wiki/Zstd says it's .zts :)

You mean `.zst` not `.zts` right?

2023-08-07 14:59 UTC, rfay commented
Sorry, its always been backwards in my fingers. I wonder how many times I've messed that up in the past.

2023-08-07 17:32 UTC, mattstein approved these changes

2023-08-07 19:39 UTC, rfay commented
Since this is your first PR I have to approve test runs, so ping me when you push new stuff, thanks!

2023-08-09 23:30 UTC, rfay requested changes
This is looking great, and a great contribution, thanks.

I find that `ddev export-db --zst` doesn't output a zstd file though, it outputs a gzipped file. Please check that (and the other uses) and make sure they're all working. A little test coverage may be useful to make sure we don't have regressions in this area.

```
$ ddev export-db --zstd --file=db.sql.zst
Wrote database dump from project 'd10' database 'db' to file db.sql.zst in gzip format.
rfay@rfay-tag1-m1:~/workspace/d10/.tarballs$ file *.zst
db.sql.zst: gzip compressed data, from Unix, original size modulo 2^32 12219647
```

2023-08-11 15:51 UTC, kringkaste commented
Sorry @rfay but I'm getting stalled here. To make zstd compression available for export-db, the zstd package have be added to the db-server images. But the base image for mariadb 5.5 is so old, the package is not available in the used distribution.  All other db images can be build.

Do we find a solution for that? If so, I would add test coverage.

2023-08-11 18:03 UTC, rfay commented
It's OK to exclude it for mariadb 5.5. We have to do that for postgres:9, it can't do snapshots. You might have to make an "if can't then error" 

Thanks for the great work!

2023-08-11 18:05 UTC, rfay commented
It's also possible to do the compression work on the host/golang side. But no need to worry about that. 

We'll need new images if you're changing those though, you can push your own to your own account temporarily or I can push some up when you're ready. Don't forget about postgres.

2023-08-11 18:34 UTC, rfay commented
I also wonder if anybody EVER uses the old mysql and mariadb versions. They're there to help revive old websites, but wow, they are really getting old now. They weren't so old 7 years ago.

2023-08-30 23:20 UTC, rfay commented
Hoping you'll be back to this before it gets so stale it's unrecoverable @kringkaste . You've done great work on it.

2023-09-05 14:55 UTC, rfay commented
Happy to help get this to completion, but if it's not active before about Sept 15, I'll close it. That doesn't mean we can't reopen it, etc, but it needs to not be cluttering the queue if it's not making progress.

2023-09-19 20:28 UTC, rfay commented
Thanks for all the work on this. If you get back to it I'm happy to help and we can re-open it. Closing for now.

2023-09-19 20:28 UTC, closed without merging