docs: add next steps to improve guiding new users through the docs (ux)
ddev/ddev pull request #5279
Opened 2023-08-19 10:00 UTC by mandrasch

## The Issue

Thought about some UX improvements for the docs start page:

1. new users will often begin their "user journey" on https://ddev.readthedocs.io/en/latest/
1. "System Requirements" section contain external links to Docker Desktop, Colima, etc <br> --> users might exit the process of following next steps ("bounce rate")
1. no call to actions at the end of the start page <br> --> users might exit the process of following next steps ("bounce rate")

Especially the gitpod & codespaces section provides no further link, I completely missed the sub-section https://ddev.readthedocs.io/en/latest/users/install/ddev-installation/#github-codespaces when I explored codespaces.

<img width="743" alt="image" src="https://github.com/ddev/ddev/assets/777278/e61127f5-22c6-4ac1-a88e-b80f8134cbee">

<img width="736" alt="image" src="https://github.com/ddev/ddev/assets/777278/648ad587-55ff-400d-955a-ccfdfdcf297c">

## How This PR Solves The Issue

First I thought about a "next / prev" nav (screenshot example of [vitepress](https://my-ddev-lab.mandrasch.eu/):

<img width="736" alt="image" src="https://github.com/ddev/ddev/assets/777278/01241eaa-d289-4b85-a32c-a2769dcddefe">

But Windows and Linux users would need to re-select the Linux Tab on all upcoming page navigations, therefore not the best solution from UX standpoint.

**Therefore I would like to propose a "next steps" section:**

<img width="758" alt="image" src="https://github.com/ddev/ddev/assets/777278/c25563b8-6794-483f-9664-0b8dbdb2cfc2">

The rocket emoji is of course a matter of personal taste.

Please feel free to change this in any way it fits to DDEV style (if relevant). 🤗

General side notes: 

- The entry page https://ddev.readthedocs.io/en/latest/ could also get more prominent links to Discord, Newsletter, Social Profiles - all the important things to integrate new people into the DDEV community. Don't know how many users start their journey there, but guess its a good portion (next to ddev.com and github repository page)?
- Partners or contributors could be shown there as well to promote trust in DDEV (depends on the goals), see e.g. https://docs.astro.build/en/getting-started/ , https://kit.svelte.dev/docs/introduction, https://nextjs.org/docs for inspiration

## Manual Testing Instructions

- test if links really work
- [x] tested links locally with workaround command `docker run -it -p 8000:8000 -v "${PWD}:/docs" -e "ADD_MODULES=mkdocs-material mkdocs-redirects mkdocs-minify-plugin mdx_truly_sane_lists mkdocs-git-revision-date-localized-plugin" -e "LIVE_RELOAD_SUPPORT=true" -e "FAST_MODE=true" -e "DOCS_DIRECTORY=./docs" polinux/mkdocs:1.2.3`

## Automated Testing Overview

- just docs

## Related Issue Link(s)

## Release/Deployment Notes

2023-08-20 00:08 UTC, rfay reviewed
This is a very good idea.

2023-08-21 15:45 UTC, mattstein requested changes
Thanks for the PR!

The MkDocs Material theme here has some footer paging links that apparently disappeared because they went opt-in only at some point:

<img width="1263" alt="Screen Shot 2023-08-21 at 08 35 03 AM@2x" src="https://github.com/ddev/ddev/assets/2488775/68b47793-d40f-45af-b24a-4471c1b6fad2">

They’re much easier to miss compared to the VitePress links that are part of the page content, but if you think it might help you’re welcome to add `- navigation.footer` to the `theme:` section in `docs/mkdocs.yml`.

Regardless, this is a nice way to encourage someone to move confidently along the setup process! 🙌

2023-08-21 15:45 UTC, mattstein commented on docs/content/index.md
> +    1. Launch your [first project](users/project) and start developing 🚀
I’d number these sequentially, punctuate consistently, and drop the parentheses in item one:

```suggestion
    1. Install Colima or Docker Desktop with [recommended settings](users/install/docker-installation.md#macos).
    2. Install [DDEV for macOS](users/install/ddev-installation.md#macos).
    3. Launch your [first project](users/project) and start developing. 🚀
```

2023-08-21 15:45 UTC, mattstein commented on docs/content/index.md
> +    You’ll need a Docker provider on your system before you can install DDEV.
The other intros use italics, so might as well here:

```suggestion
    *You’ll need a Docker provider on your system before you can install DDEV.*
```

2023-08-21 15:45 UTC, mattstein commented on docs/content/index.md
> +    1. Launch your [first project](users/project) and start developing 🚀
```suggestion
    1. Install Docker with [recommended settings](users/install/docker-installation.md#windows).
    2. Install [DDEV for Windows](users/install/ddev-installation.md#windows).
    3. Launch your [first project](users/project) and start developing. 🚀
```

2023-08-21 15:45 UTC, mattstein commented on docs/content/index.md
> +    1. Launch your [first project](users/project) and start developing 🚀
```suggestion
    1. Install Docker with [recommended settings](users/install/docker-installation.md#windows).
    2. Install [DDEV for Windows](users/install/ddev-installation.md#windows).
    3. Launch your [first project](users/project) and start developing. 🚀
```

2023-08-21 15:45 UTC, mattstein commented on docs/content/index.md
> +    1. Launch your [first project](users/project) and start developing 🚀
```suggestion
    1. Install Docker with [recommended settings](users/install/docker-installation.md#linux).
    2. Install [DDEV for Linux](users/install/ddev-installation.md#linux).
    3. Launch your [first project](users/project) and start developing. 🚀
```

2023-08-22 05:44 UTC, mandrasch commented
Thanks very much for reviewing / updating @mattstein!

Accepted your changes, good to go: 

Also added the next/prev links at the bottom, think they could motivate some users to check out next chapters (maybe).

https://ddev--5279.org.readthedocs.build/en/5279/

Good to go from my point of view.

2023-08-23 16:51 UTC, mattstein approved these changes

2023-08-23 16:55 UTC, merged