refactor: remove support for nodejs version 14
ddev/ddev pull request #5405
Opened 2023-10-08 18:36 UTC by amayer5125

Node 14 went end of life in April 2023. New versions of the Node installer do not support version 14.

## The Issue

NodeJS version 14 is [end of life](https://endoflife.date/nodejs).

## How This PR Solves The Issue

This pull request removes support for version 14.

## Release/Deployment Notes

Users using Node 14 will need to upgrade.

2023-10-08 18:43 UTC, rfay commented
Thanks, don't forget 
* https://ddev.readthedocs.io/en/latest/users/configuration/config/#nodejs_version
* https://ddev.readthedocs.io/en/latest/users/usage/commands/#config (which is already incorrect, mentioning 16. We should be able to do better words there. Just change to "if you don't want to use the default version"

2023-10-09 12:56 UTC, rfay approved these changes
This looks perfect to me, thanks. After it goes in you can rebase and finish the other one.

2023-10-09 13:25 UTC, stasadev requested changes
Found one more place with `14`:

https://github.com/ddev/ddev/blob/d3e6e5b54296fa3ec421da9bd9424db71e01aae0/pkg/ddevapp/templates.go#L66

Please update and it will be ready to go.

2023-10-09 13:27 UTC, rfay commented
You can push that one more commit with `[skip ci]` in the title - it doesn't need another test run.

2023-10-09 13:54 UTC, amayer5125 commented
@rfay change pushed.

2023-10-09 13:58 UTC, stasadev approved these changes

2023-10-09 14:06 UTC, merged