fix: supervisord should not bring down the whole web container when non-essential service fails, fixes #5358
ddev/ddev pull request #5423
Opened 2023-10-13 15:57 UTC by mootensai

## The Issue
When a command that runs by the Supervisor gets an error or crash, it automatically turns off the web container. Making the supervisor auto restart feature useless.

## How This PR Solves The Issue
This PR check when there's an error happen in supervisord whether nginx or apache is working properly or not. if one of them is down, kill supervisord

## Manual Testing Instructions
I cannot test this on real use case because I need the file to run when supervisord start. please guide me how to test this in my env.

## Automated Testing Overview
I cannot test this because of the same reason above.

## Related Issue Link(s)
https://github.com/ddev/ddev/issues/5358

## Release/Deployment Notes
this shouldn't affect anything else.

2023-10-13 16:00 UTC, rfay commented
Thanks! This will require a custom image to be pushed, I'll try to do it in the coming days.

2023-10-13 17:39 UTC, rfay commented
Actually it would be good for you to test this manually before we start pushing images. I think you know all the details of what to do, but update the `kill_supervisor.py` inside the container after it's running, and then test your scenario. You can use `docker cp` to copy it in there, or you can copy it from a mounted directory.

I thought you would just be making small changes to the supervisord.conf rather than trying to make the kill script fancy.

2023-10-13 19:37 UTC, mootensai commented
OK I'll try this now. I'm putting it in web-build & add a Dockerfile to ADD to replace the original kill_supervisor.py

2023-10-13 20:31 UTC, mootensai commented
It works well with my current configuration. But I don't know how to make Apache or Nginx errors to ensure the container will turn off when that happens.

2023-10-14 05:32 UTC, rfay commented
You can just `ddev exec killall apache2` or `ddev exec killall nginx` or `ddev exec killall php-fpm`

2023-10-14 13:32 UTC, rfay requested changes
Questions about php-fpm and gunicorn for discussion.

2023-10-14 13:32 UTC, rfay commented on containers/ddev-webserver/ddev-webserver-base-files/usr/local/bin/kill_supervisor.py
> +            if (not isApacheAlive and not isNginxAlive and isSupervisordAlive):
Seems like we're missing php-fpm and gunicorn here. 

But we should have apache OR nginx
and php-fpm OR gunicorn

right?

2023-11-07 23:29 UTC, rfay commented
Let me know if you're interested in continuing with this, otherwise I'll close it about November 15.

2023-11-07 23:33 UTC, mootensai commented
I'm interested in continuing this issue. it's halfway done but I'm currently got no time. I'll try to fix this before November 15th.

2023-11-18 01:31 UTC, rfay commented
Closing this for now, happy to return to it later, it can be reopened. Thanks for this contribution and all the thinking that went into it.

2023-11-18 01:31 UTC, closed without merging