fix: always include pre-releases on version constraint checking
ddev/ddev pull request #5424
Opened 2023-10-13 22:41 UTC by hanoii

## The Issue

With the new version constraint #5379, it was reported on both the PR as well as on https://github.com/ddev/ddev/issues/4630#issuecomment-1761998687 that it's not clear or is confusing why a built version like `v1.22.3-24-g3d90d5eeb` is not accepted with a constraint of `>= v1.22`. This is because of https://github.com/Masterminds/semver#checking-version-constraints.

## How This PR Solves The Issue

This assumes that pre-releases are always included. While this invalidates any mean of "excluding" pre-releases with the constraint, for general usage this will lead to less support issues and matches other less strict constraints comparisons.

## Manual Testing Instructions

`ddev config --ddev-version-constraint=">= 1.22"` should work.

2023-10-14 12:28 UTC, rfay commented
Should we have just used comparison instead of constraint, for more predictable behavior?

2023-10-14 12:40 UTC, rfay requested changes
This seems to be on the right track. We need to give improved guidance to the user. Thanks for all the work on this!

2023-10-14 12:40 UTC, rfay commented on pkg/ddevapp/config.go
> +				return fmt.Errorf("ddev version %v is not supported by this project (%v), use a supported version or update your project config.yaml's `ddev_version_constraint`", versionconstants.DdevVersion, ap
We need to improve this. I was pretty confused by

```
$ ddev config --ddev-version-constraint=">=v1.22.4"
You are reconfiguring the project at /Users/rfay/workspace/d10.
The existing configuration will be updated and replaced.
Configuring a 'drupal10' codebase with docroot 'web' at /Users/rfay/workspace/d10/web
failed to validate config: ddev version v1.22.3-35-g4e684a83a is not supported by this project (>=v1.22.4), use a supported version or update your project config.yaml's `ddev_version_constraint`
```

```suggestion
				return fmt.Errorf("This project has a DDEV version constraint of '%s' and the version of DDEV you are using ('%s') does not meet the constraint. Please update the `ddev_version_constraint` in your .ddev/config.yaml or use a version of DDEV that meets the constraint.", app.DdevVersionConstraint, 
 versionconstants.DdevVersion)
```

2023-10-14 15:53 UTC, hanoii commented
@rfay 
> We need to give improved guidance to the user.

Is this your text change suggestion? That's committed, not sure if you meant something else.

2023-10-14 18:07 UTC, rfay commented
> Is this your text change suggestion? That's committed, not sure if you meant something else.

Yes, thanks, I made the comment and then realized I could just suggest.

Sorry I capitalized wrong!

2023-10-14 23:21 UTC, hanoii commented
tests are failing on the last commit but it was really a comment change, and looking at them looks unrelated

2023-10-15 06:45 UTC, rfay commented
It was just the Colima tests, which are always fragile (because of the Github-hosted runner). I restarted it. You should have been able to restart also, right?

2023-10-16 12:34 UTC, merged

2023-10-19 12:09 UTC, deviantintegral commented
I just tested the build in this issue and this feature works nicely. Thank you!