feat: `pre-cmd` and `post-cmd` hooks
ddev/ddev pull request #5448
Opened 2023-10-23 21:14 UTC by hanoii

I am looking for ways to do more automations within ddev rather than on the host, and I wanted a hook that I can hook that it's run on every ddev command. I thought of different ways and came up with  pre-cmd and post-cmd command.

For now this is an idea, it works and does what I need, not fully tested but didn't want to lose what I did without sharing.

More context on https://discord.com/channels/664580571770388500/1144344589549973636/1166023601540051004

2023-10-23 21:34 UTC, rfay commented
Looks like you have some work to do yet. I guess my comment just from the title is I'd be more in favor of `pre-command` and `post-command`

2023-10-23 21:52 UTC, hanoii commented
Renamed and push a fix for the tests, let's see 🤞

2023-10-24 13:36 UTC, hanoii commented
Once I start working on some ddev feat is hard to stop :D

I continued working on this, it's looking working nicely I think, I've updated the PR description with more details.

I want to run an idea by you... I started adding hooks arguments, for now they do nothing (at first I needed it for some validation I was doing on `ProcessHooks()` but in the end I didn't need them. But I think this is also a nice addition. Basically I want to make available the COMMAND being run to the hook so that it can be used if needed. I thought of some non-invasive way of doing and I thought of adding something like:

`DDEV_HOOKS_PRE_COMMAND_ARG0`   environment variable to the os.Exec(). I've looked and I think this can be used for any hook (exec, exec-host, etc..). I would do in such a way that any arguments can be used in any hook. Another usage would be the db being imported on pre-import-db and post-import-db if you have multiple databases.

Would you want me to explore this here, or remove it and work on it on a separate PR.

2023-10-31 22:40 UTC, rfay commented
Rebased, I will get to it.

2023-11-10 17:57 UTC, rfay commented
Rebased.

2023-11-10 18:11 UTC, rfay requested changes
You snuck args to tasks in here without mentioning it in the OP or updating the docs. It really should have been in a separate PR.

However, please update the PR OP with a description of this feature and how it's intended to work. 

And please add to the docs.

My simple manual testing of the base feature (pre-command and post-command hooks) worked fine. 

Do you have test coverage for the args feature?

2023-11-15 19:33 UTC, stasadev reviewed
If these hooks produce output and you use the `--json-output` flag, it may break the PhpStorm plugin for DDEV:

```
de.php_perfect.intellij.ddev.cmd.CommandFailedException: Failed to parse output of command 'ddev describe --json-output': pre-command exec
pre-command exec-host
{"level":"info","msg":"..."}
post-command exec
post-command exec-host
```

2023-11-15 22:32 UTC, rfay commented
> If these hooks produce output and you use the --json-output flag, it may break the PhpStorm plugin for DDEV

That would be really, really annoying to anything that does a `ddev exec` or `ddev describe -j` running those hooks. Of course... if you install the hooks you should deal with it. But I agree that this could create a number of new complaints from people expecially using the PhpStorm extension. Unintended consequences.

2023-11-22 13:21 UTC, rfay commented
Could you please make a clearer statement about exactly why you want this? It would have been better to start with an issue for discussion. Please be clear about how this will benefit you and also how it can help the general DDEV community.

2023-11-22 13:47 UTC, hanoii commented
@rfay added #5557

2023-12-15 21:30 UTC, rfay commented
All your many contributions are so appreciated, but I think this one is just too tweaky, and nobody but you will know why or how it exists, so I'm not going to go with it. Thanks for all the effort and skill applied to it!

2023-12-15 21:30 UTC, closed without merging