refactor: update to Node.js v20 LTS as current default
ddev/ddev pull request #5453
Opened 2023-10-24 14:27 UTC by peter-neumann-dev

## The Issue

Today, Node.js v20 has its active LTS start. As explained in the documentation: The default for the config option `nodejs_version` is the current LTS version.

## How This PR Solves The Issue

This PR raises the default used Node.js version from 18 to 20

## Manual Testing Instructions

## Automated Testing Overview

## Related Issue Link(s)

## Release/Deployment Notes

2023-10-24 14:33 UTC, rfay commented
I think 18 remains LTS for some time yet, doesn't it? https://endoflife.date/nodejs

2023-10-24 14:35 UTC, rfay commented
From https://nodejs.dev/en/about/releases/ :

<img width="1017" alt="image" src="https://github.com/ddev/ddev/assets/112444/deb14bf6-ac6e-47ae-a335-a23047e9522e">

2023-10-24 14:36 UTC, rfay commented
And I should have said at the first: Thanks for tracking this and contributing!

2023-10-24 14:39 UTC, peter-neumann-dev commented
Hi @rfay, 

thank you! I thought about Issue vs PR, but my mind was: Come on you can do this as well … At least the preparation 😄 

I checked the release schedule of Node.js here: https://github.com/nodejs/release#release-schedule
![CleanShot 2023-10-24 at 16 36 52@2x](https://github.com/ddev/ddev/assets/75690659/7ad9d437-ee44-4a82-b586-85d585bcd79e)

Also since today 20 is listed as LTS on https://nodejs.org/en
![CleanShot 2023-10-24 at 16 36 10@2x](https://github.com/ddev/ddev/assets/75690659/6ba0fd0c-d58f-418c-b726-348bfe66acf9)

Maybe the other resources will get updated later today or the next days 🙂

2023-10-24 14:55 UTC, peter-neumann-dev commented
They are on it, it's called Iron this time:
![CleanShot 2023-10-24 at 16 54 07@2x](https://github.com/ddev/ddev/assets/75690659/4e80a312-b5ba-455e-985f-b5651ecdea54)

2023-10-24 15:04 UTC, rfay commented
This won't be able to go in until DDEV v1.23.0, which is likely in the Spring of 2024. Do you want to pursue it now anyway? I do very much appreciate you keeping us up-to-date and paying attention!

2023-10-24 15:16 UTC, peter-neumann-dev commented
Sure, no problem, I was changing it in another project where I set up DDEV and saw it was 18 by default.

Should we add this to the documentation [here](https://ddev.readthedocs.io/en/stable/users/configuration/config/#nodejs_version), because 18 as the default is not the "current LTS version" or "active LTS version" anymore, instead "maintenance LTS version"? Maybe in a separate PR or something 🙂

The release table is now updated on GitHub: https://github.com/nodejs/Release#release-schedule
Here is the current LTS release: https://github.com/nodejs/node/releases/tag/v20.9.0

2023-10-24 15:22 UTC, rfay commented
The "latest" docs are at https://ddev.readthedocs.io/en/latest/users/configuration/config/#nodejs_version, so that's a *little* better. Not sure exactly how to do interim docs about this. It's not *that* important to most people. 

One of the biggest concerns I have is that we put a `nodejs_version` in the config.yaml by default, and I wish we didn't, because they get old so fast.

2023-10-24 15:27 UTC, peter-neumann-dev commented
That's an argument 👍🏻 Would the version get updated in exiting `config.yaml` files?

2023-10-24 15:52 UTC, peter-neumann-dev commented
Ok, I understand. I assumed the changes I did to raise the default version to 20 will only be noticeable when creating a new project without any existing `node_version`, why I thought it is not a problem, because for new projects that's what you want 🙂

2023-10-24 15:54 UTC, rfay commented
You might be right... We'll think about it. Maybe it's not even intrusive.

2023-10-24 20:09 UTC, rfay requested changes
Since some of the code changed here is in the ddev-php-base Dockerfile, for example, this requires a push of that and of ddev-webserver. I'll change this to "draft" until we get that done.

2023-11-03 02:53 UTC, rfay commented
This is pushed with the image now. I'm not 100% convinced about it, but now it's testable. Moving to "ready to review"

2023-11-15 18:47 UTC, stasadev approved these changes
Looks good!

```
$ ddev exec node -v
v20.9.0
```

As for when to make the switch, I'm good with any decision.

By the way, a few days ago AWS Lambda released a managed runtime for Node.js 20 https://aws.amazon.com/blogs/compute/introducing-the-amazon-linux-2023-runtime-for-aws-lambda/

2023-11-18 03:06 UTC, rfay commented
Rebased and pushed updated image. For testing, update using `docker pull ddev/ddev-webserver:20231024_peter-neumann-dev_nodejs_v20_lts`

2023-11-20 17:12 UTC, rfay commented
This will need to wait for DDEV v1.23.

2024-02-13 17:00 UTC, rfay commented
Working on this, rebased, trying to run the php-base image build, getting an unexpected failure, easy to recreate locally.

2024-02-14 03:41 UTC, merged