fix: ensure no duplicates for docker networks, fixes #5193
ddev/ddev pull request #5508
Opened 2023-11-07 20:33 UTC by stasadev

## The Issue

- #5193

## How This PR Solves The Issue

DDEV should remove Docker networks by ID, not by name. This way users won't need to worry about duplicate networks, because they will be removed automatically on `ddev start` and `ddev poweroff` - regardless of what users run.

## Manual Testing Instructions

```
# download the binary from the trird comment (this is a special broken binary that creates duplicate networks)
# and use it for ddev start, the more you do it, the more duplicates will be created
ddev start
ddev start
ddev start

# then run poweroff (networks will not be removed)
ddev poweroff

# see a lot of duplicates for ddev_default and ddev-your-project_default
docker network ls

# switch the binary to the one in the second comment and run

ddev start

# you will see a lot of these:

Network ddev_default removed
Network ddev_default removed

You seem to have a new DDEV version. 
During an upgrade it's important to `ddev poweroff`.
May I do `ddev poweroff` before continuing?
This does no harm and loses no data. [Y/n] (yes): y

# Answer "yes", and all duplicates will be removed on ddev poweroff

Network ddev-project_default removed 
Network ddev-project_default removed 
Network ddev-project_default removed
Network ddev_default removed
Network ddev-php-2023_default removed 
Network ddev-php-2023_default removed

# Also you can repeat the same steps but this time answer "no" and then run ddev start, the duplicates will also be removed

May I do `ddev poweroff` before continuing?
This does no harm and loses no data. [Y/n] (yes): n

ddev start

Starting project... 
Network ddev-project_default removed 
Network ddev-project_default removed 
Network ddev-project_default removed
```

## Automated Testing Overview

## Related Issue Link(s)

## Release/Deployment Notes

2023-11-07 20:41 UTC, stasadev commented
This is a special broken binary that creates duplicate networks:

## Use it only for this PR testing

* [all-ddev-executables.zip](https://nightly.link/ddev/ddev/actions/artifacts/1034925836.zip)
* [ddev-linux-amd64.zip](https://nightly.link/ddev/ddev/actions/artifacts/1034925838.zip)
* [ddev-linux-arm64.zip](https://nightly.link/ddev/ddev/actions/artifacts/1034925840.zip)
* [ddev-macos-amd64.zip](https://nightly.link/ddev/ddev/actions/artifacts/1034925842.zip)
* [ddev-macos-arm64.zip](https://nightly.link/ddev/ddev/actions/artifacts/1034925844.zip)
* [ddev-windows-amd64-installer.zip](https://nightly.link/ddev/ddev/actions/artifacts/1034925846.zip)

2023-11-08 08:20 UTC, jonaseberle commented
I never had the duplicate networks on Linux (docker v24.0.5), but with your "broken" build I can reproduce.
The current `master` shows many warnings then:
On `ddev start` (v1.22.5-alpha1-3-g0225d6f48):

multiple networks with name "ddev_default" were found. Use network ID as `name` to avoid ambiguity 
Failed to start shop.lash-lift.de: composeCmd failed to run 'COMPOSE_PROJECT_NAME=ddev-shoplash-liftde docker-compose -f /home/jonas/src/github.com/lmwa/lashlift-shopware-project/.ddev/.ddev-docker-compose-full.yaml up -d', action='[]', err='exit status 1', stdout='', stderr='multiple networks with name "ddev_default" were found. Use network ID as `name` to avoid ambiguity'

On `ddev poweroff` (v1.22.5-alpha1-3-g0225d6f48):

Unable to remove network ddev_default: API error (400): network ddev_default is ambiguous (5 matches found based on name) 
Unable to remove network ddev-shoplash-liftde_default: API error (400): network ddev-shoplash-liftde_default is ambiguous (3 matches found based on name)

With this PR (v1.22.5-alpha1-4-g8ccbe6ba1) they get removed on `ddev start`. So that works for me.

But I am not sure if network removal should be in `NetExists()`. It seems a bit overloaded to me in such a seemingly simple function. 
I think it would be nicer in `EnsureNetwork()` (to prevent duplicates being created - if we still have that problem on docker for Mac) and/or the `RemoveNetwork...(name)` functions (they could really remove all networks with that name to clean up from potential stray networks from older versions).

2023-11-08 15:36 UTC, stasadev commented
@jonaseberle Thank you!

>I am not sure if network removal should be in `NetExists()`. It seems a bit overloaded to me in such a seemingly simple function.

I agree, I thought just one "for" loop for networks would be good, but now it's not clear what's going on with the function name. I will create a new function to remove duplicates.

I need to think more about `RemoveNetwork...(name)`, showing `Network ddev-your-project_default removed` is not helpful for duplicates, maybe I can suppress this output in this case so the user doesn't even have to worry about it.

>We also have the network labels that we added in 1.22.4. I am not sure if we are using them in `ddev poweroff` correctly already.

We use them to remove all leftovers from Docker, so if something goes wrong it'll still be cleaned up here.

It's true that currently duplicates cannot be removed in v1.22.4 (because of the check for network name, not ID), but with my change in this PR it will finally be handled properly.

2023-11-09 20:04 UTC, stasadev commented
I made a new function `RemoveNetworkDuplicates`, and tried to simplify the code.

The first post of this PR now has a summary where I've gathered all the information about this issue in one place.

2023-11-10 17:02 UTC, rfay requested changes
The code is looking great, but when I `ddev restart` I get errors like this:
```
$ ddev restart d10
Restarting project d10...
 Container ddev-d10-db  Stopped
 Container ddev-d10-web  Stopped
 Container ddev-d10-db  Stopped
 Container ddev-d10-web  Stopped
 Container ddev-d10-db  Removed
 Container ddev-d10-web  Removed
Unable to remove network ddev-d10_default: API error (403): error while removing network: network ddev-d10_default id 169ec45f14920cef6a487cc8be020647f9d81e69187a53d7d37464b61aa103fd has active endpoints
```

This is using orbstack, I doubt that matters.

2023-11-10 17:10 UTC, rfay commented
That problem was due to an abandoned container left by a removed add-on (xhgui). I don't think it has anything to do with this.

2023-11-10 17:36 UTC, rfay approved these changes
I manually tested with the broken ddev that creates extra networks, and it works perfectly with the manual testing technique. 

I looked at the code and it's elegant and nice. Thanks! 💯

2023-11-10 20:03 UTC, merged