Update projecttype list templates.go
ddev/ddev pull request #5546
Opened 2023-11-16 22:10 UTC by ayacoo

2023-11-16 22:29 UTC, rfay requested changes
Just missed a thing or two. Did you want magento in there also? 

The official list is `backdrop, craftcms, django4, drupal10, drupal6, drupal7, drupal8, drupal9, laravel, magento, magento2, php, python, shopware6, silverstripe, typo3, wordpress`

2023-11-16 22:29 UTC, rfay commented on pkg/ddevapp/templates.go
>  # type: <projecttype>  # drupal6/7/8, backdrop, typo3, wordpress, php, craftcms, laravel, magento2, shopware6, silverstripe
```suggestion
# type: <projecttype>  # drupal6/7/8/9/10, backdrop, typo3, wordpress, php, craftcms, laravel, magento2, shopware6, silverstripe
```

2023-11-16 22:30 UTC, rfay commented on pkg/ddevapp/templates.go
> +# information on the different projecttypes
```suggestion
# information on the different project types
```

2023-11-16 22:38 UTC, ayacoo commented
Firstly, thank you for your support :-)

I was confused by the documentation here because project type "magento" was not mentioned there: https://ddev.readthedocs.io/en/latest/users/quickstart/#magento (tab "OpenMage/Magento 1")

Django is tagged as "experimental". That's why I was unsure.

I have taken the liberty of adopting your list, including alphabetical sorting. This is otherwise rather difficult to read

2023-11-18 01:28 UTC, rfay approved these changes
Thanks!

2023-11-18 13:08 UTC, merged