fix: global project_tld should default to 'ddev.site', not empty, fixes #4290
ddev/ddev pull request #5632
Opened 2023-12-14 21:25 UTC by rfay

## The Issue

* #4290

@rpkoller pointed out that the global_config.yaml would be more useful if it just *specified* ddev.site as the project_tld.

## How This PR Solves The Issue

Make it explicit in the config.

## Manual Testing Instructions

- [ ] Test to make sure changing global project_tld still works fine
- [ ] Test to make sure default config with ddev.site works fine. Automated tests ought to do this just fine.

2023-12-18 10:53 UTC, stasadev requested changes
Noticed a bug, it's not even related to the changes made in this PR (reproducible on the stable DDEV), but it probably fits here:

When you set the global TLD to `test` and the project TLD to `ddev.site`, the project config is not set, it seems that there is some hardcode in the code for `nodeps.DdevDefaultTLD`:

```
ddev config global --project-tld test
ddev config --project-tld ddev.site
```

On the other hand, this override works if I set it manually: `project_tld: ddev.site` in `.ddev/config.yaml`. But it is lost when I run `ddev config --auto` or `ddev config --project-tld ddev.site`.

2023-12-19 22:13 UTC, rfay commented
OK with me for you to fix that here.

2023-12-20 19:17 UTC, stasadev commented
I made a change in the `app.WriteConfig()`, will see how the tests go.

2023-12-21 17:55 UTC, stasadev approved these changes

2023-12-25 18:18 UTC, stasadev commented
It should be fine, I tested it again and didn't find any flaws.

2023-12-25 18:19 UTC, merged