Link to Python Flask and Django 4
ddev/ddev pull request #5638
Opened 2023-12-16 15:27 UTC by jeroenpeters1986

Added links to the Quickstarts from the experiment page

## The Issue
As I stated in issue#5171, I overlooked the quickstarts the first time, so I put helpful links

## How This PR Solves The Issue
It adds links

## Manual Testing Instructions
None

## Automated Testing Overview
No tests needed for docs

## Related Issue Link(s)
As I stated in issue#5171, I overlooked the quickstarts the first time, so I put helpful links

## Release/Deployment Notes
None

2023-12-16 15:32 UTC, jeroenpeters1986 commented
@rfay I'm sorry, I copied the content of the PR but forgot to edit the title :-( I cant seems to run a re-check for the title myself

2023-12-16 15:44 UTC, rfay commented
The failure seems to be markdownlint now, not the title, https://github.com/ddev/ddev/actions/runs/7232772716/job/19707303814?pr=5638

2023-12-16 15:44 UTC, rfay approved these changes
I'm so glad you added this!

2023-12-16 17:06 UTC, jeroenpeters1986 commented
Thanks, glad to do so!Op 16 dec 2023 om 16:45 heeft Randy Fay ***@***.***> het volgende geschreven:﻿
@rfay approved this pull request.

I'm so glad you added this!

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-12-18 00:15 UTC, mattstein requested changes
I’d recommend adding a space, but otherwise looks good to me!

2023-12-18 00:15 UTC, mattstein commented on docs/content/users/configuration/experimental.md
> +To get started with either one of these Python projects, checkout the [Django4 Quickstart](../quickstart/#django-4-experimental) or the [Flask Quickstart](../quickstart/#pythonflask-experimental).
This needs a space to be consistent with the page it links to and [Django’s own formatting](https://docs.djangoproject.com/en/4.1/releases/4.0/): 

```suggestion
To get started with either one of these Python projects, checkout the [Django 4 Quickstart](../quickstart/#django-4-experimental) or the [Flask Quickstart](../quickstart/#pythonflask-experimental).
```

2023-12-18 08:09 UTC, jeroenpeters1986 commented
Sorry for all the commits and runs guys, but it's finally ok :-D

2023-12-18 11:29 UTC, stasadev approved these changes

2023-12-19 19:38 UTC, merged