docs: Overhaul Shell Completion & Autocomplete documentation
ddev/ddev pull request #5701
Opened 2024-01-17 07:39 UTC by Nick-Hope

## The Issue

The 'Shell Completion & Autocomplete' documentation page is difficult to follow and comprehend due to duplication and, in parts, convoluted logic. In particular, there is repetition of the instructions for obtaining the tar archive of completion scripts, and such instructions vary. DDEV version numbers also vary and are outdated in various places.

## How This PR Solves The Issue

Overhaul of much of the page for clarification, conciseness, updating of version numbers, and to avoid duplication. In particular, provide instructions for obtaining the tar archive of completion scripts in **just one place**, and link to it from the individual instructions for specific scripts.

## Automated Testing Overview

No tests needed. Just documentation.

2024-01-17 11:59 UTC, stasadev commented
Hi @Nick-Hope,

Thank you, I haven't reviewed this PR yet, just had a quick look at the formatting on the page, some code blocks needs to be reformatted, you can view your changes online in the browser:

https://ddev.readthedocs.io/en/latest/developers/testing-docs/#fix-docs-using-web-browser

> Once the PR has run its checks, you’ll see an item labeled `docs/readthedocs.org:ddev`. Click “Details” to review a docs build that includes your changes

Here is the link https://ddev--5701.org.readthedocs.build/en/5701/users/install/shell-completion/

2024-01-17 17:02 UTC, Nick-Hope commented
@stasadev I got there in the end. The triple backticks are not being rendered now. Apologies if my multiple attempts caused you too many notifications.

2024-01-23 18:04 UTC, stasadev requested changes
@Nick-Hope,

No problems with notifications 🙂

Thank you for your efforts to make it easier to work with DDEV!

2024-01-24 12:42 UTC, stasadev approved these changes
Thank you!

And for future reference, you can apply all GitHub suggestions in one commit when you view them from the [Files changed](https://github.com/ddev/ddev/pull/5701/files) tab, "Add suggestion to batch" button is available there.

2024-01-26 19:53 UTC, merged