Added support to pull data from specific APP in case you have more th…
ddev/ddev pull request #5728
Opened 2024-01-23 12:31 UTC by nir-riskified

…an one app under your env.

## The Issue

## How This PR Solves The Issue

## Manual Testing Instructions

## Automated Testing Overview

## Related Issue Link(s)

## Release/Deployment Notes

2024-01-23 17:20 UTC, stasadev requested changes
I haven't actually tested platform integration with `--app`, but I suggest a more elegant way of writing the condition.

Used `${parameter:+word}` from https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html

> If parameter is null or unset, nothing is substituted, otherwise the expansion of word is substituted.

2024-01-23 17:20 UTC, stasadev commented on pkg/ddevapp/dotddev_assets/providers/platform.yaml
> +# 3. Add PLATFORM_PROJECT and PLATFORM_ENVIRONMENT and PLATFORM_APP(optional) variables to your project `.ddev/config.yaml` or a `.ddev/config.platform.yaml`
```suggestion
# 3. Add PLATFORM_PROJECT and PLATFORM_ENVIRONMENT and PLATFORM_APP (optional) variables to your project `.ddev/config.yaml` or a `.ddev/config.platform.yaml`
```

2024-01-23 17:20 UTC, stasadev commented on pkg/ddevapp/dotddev_assets/providers/platform.yaml
> +    PLATFORM_RELATIONSHIPS="" platform relationships -y  -e "${PLATFORM_ENVIRONMENT}" $( [ -n "${PLATFORM_APP}" ] && echo "--app=${PLATFORM_APP}" ) | yq 'with_entries(select(.[][].type == "mariadb:*"
```suggestion
    PLATFORM_RELATIONSHIPS="" platform relationships -y  -e "${PLATFORM_ENVIRONMENT}" ${PLATFORM_APP:+"--app=${PLATFORM_APP}"} | yq 'with_entries(select(.[][].type == "mariadb:*" or .[][].type == "*mysql:*" or .[][].type == "postgresql:*")) ' >${db_relationships_file}
```

2024-01-23 17:20 UTC, stasadev commented on pkg/ddevapp/dotddev_assets/providers/platform.yaml
> +      platform db:dump --yes $( [ -n "${PLATFORM_APP}" ] && echo "--app=${PLATFORM_APP}" ) --relationship=${rel} --gzip --file=/var/www/html/.ddev/.downloads/${db_name}.sql.gz --project="${PLATFORM_P
```suggestion
      platform db:dump --yes ${PLATFORM_APP:+"--app=${PLATFORM_APP}"} --relationship=${rel} --gzip --file=/var/www/html/.ddev/.downloads/${db_name}.sql.gz --project="${PLATFORM_PROJECT:-setme}" --environment="${PLATFORM_ENVIRONMENT:-setme}"
```

2024-01-23 17:20 UTC, stasadev commented on pkg/ddevapp/dotddev_assets/providers/platform.yaml
> +    platform mount:download --all --yes --quiet --project="${PLATFORM_PROJECT}" --environment="${PLATFORM_ENVIRONMENT}" $( [ -n "${PLATFORM_APP}" ] && echo "--app=${PLATFORM_APP}" ) --target=/var/www
```suggestion
    platform mount:download --all --yes --quiet --project="${PLATFORM_PROJECT}" --environment="${PLATFORM_ENVIRONMENT}" ${PLATFORM_APP:+"--app=${PLATFORM_APP}"} --target=/var/www/html
```

2024-01-23 17:20 UTC, stasadev commented on pkg/ddevapp/dotddev_assets/providers/platform.yaml
> +    gzip -dc db.sql.gz | platform db:sql --project="${PLATFORM_PROJECT}" ${rel:-} --environment="${PLATFORM_ENVIRONMENT} $( [ -n "${PLATFORM_APP}" ] && echo "--app=${PLATFORM_APP}" )"
```suggestion
    gzip -dc db.sql.gz | platform db:sql --project="${PLATFORM_PROJECT}" ${rel:-} --environment="${PLATFORM_ENVIRONMENT}" ${PLATFORM_APP:+"--app=${PLATFORM_APP}"}
```

2024-01-23 17:20 UTC, stasadev commented on pkg/ddevapp/dotddev_assets/providers/platform.yaml
> +    platform mount:upload --yes --quiet --project="${PLATFORM_PROJECT}" --environment="${PLATFORM_ENVIRONMENT}" $( [ -n "${PLATFORM_APP}" ] && echo "--app=${PLATFORM_APP}" ) --source="${DDEV_FILES_DI
```suggestion
    platform mount:upload --yes --quiet --project="${PLATFORM_PROJECT}" --environment="${PLATFORM_ENVIRONMENT}" ${PLATFORM_APP:+"--app=${PLATFORM_APP}"} --source="${DDEV_FILES_DIR}" --mount=web/sites/default/files
```

2024-01-23 17:33 UTC, stasadev commented
@nir-riskified,

I checked if all changed commands have `--app` option, everything looks fine.

You can apply my suggestions in one commit on the [Files](https://github.com/ddev/ddev/pull/5728/files) tab.

And please update the [documentation file](https://github.com/ddev/ddev/blob/9d24d567065216fc1e1d85d5e2859b88a87b4728/docs/content/users/providers/platform.md) when you get a chance.

Thank you for the contribution!

2024-01-24 12:23 UTC, stasadev requested changes
@nir-riskified, I like your change in the docs with a new section for multiple apps, let's use it for information about the optional `PLATFORM_APP` instead of mixing it with other variables.

2024-01-24 12:23 UTC, stasadev commented on docs/content/users/providers/platform.md
> +2. Add `PLATFORM_PROJECT` and `PLATFORM_ENVIRONMENT` and  `PLATFORM_APP` (optional) variables to your project.
```suggestion
2. Add `PLATFORM_PROJECT` and `PLATFORM_ENVIRONMENT` variables to your project.
```

2024-01-24 12:23 UTC, stasadev commented on docs/content/users/providers/platform.md
> +        - PLATFORM_APP=app (optional)
```suggestion
```

2024-01-24 12:23 UTC, stasadev commented on docs/content/users/providers/platform.md
> +It is necessary to specify PLATFORM_APP variable under web_environment if your environment contains more than one app
````suggestion
### Multiple apps

If your environment contains more than one app, add `PLATFORM_APP` variable to your project:

    * Either in `.ddev/config.yaml` or a `.ddev/config.*.yaml` file:

        ```yaml
        web_environment:
        - ...
        - PLATFORM_APP=app
        ```

    * Or with a command from your terminal:

        ```bash
        ddev config --web-environment-add="PLATFORM_APP=app"
        ```
````

2024-01-24 12:23 UTC, stasadev commented on pkg/ddevapp/dotddev_assets/providers/platform.yaml
> +# 3. Add PLATFORM_PROJECT and PLATFORM_ENVIRONMENT and PLATFORM_APP (optional) variables to your project `.ddev/config.yaml` or a `.ddev/config.platform.yaml`
```suggestion
# 3. Add PLATFORM_PROJECT and PLATFORM_ENVIRONMENT and optional PLATFORM_APP (only if your environment contains more than one app) variables to your project `.ddev/config.yaml` or a `.ddev/config.platform.yaml`
```

2024-01-24 14:09 UTC, nir-riskified commented
Updated! Thanks @stasadev

2024-01-24 14:18 UTC, stasadev reviewed
Added one more commit with indentation fix in docs, and renamed the header "Multiple apps" to "Managing Multiple Apps".

Let's see how the tests go.

2024-01-26 19:51 UTC, stasadev approved these changes

2024-01-26 19:55 UTC, merged