docs: Update Drupal 9 & 10 CMS Quickstarts
ddev/ddev pull request #5733
Opened 2024-01-24 09:08 UTC by Nick-Hope

## The Issue

`ddev drush uli` generates a one-time link to the page for editing the uid1 (admin) account details. If the site is opened with that, there is no need to also run `ddev launch`, so that is confusing.

## How This PR Solves The Issue

Add instructions on how to open the link generated by `ddev drush uli`. Remove `ddev launch` from the initial instructions but refer to its use for further site visits.

An alternative would be to drop the `ddev drush uli` line, but then the user would not be logged in when `ddev launch` is run.

2024-01-24 13:05 UTC, stasadev approved these changes
Thank you, I think this is a reasonable improvement 👍

2024-01-24 23:59 UTC, tyler36 commented
A side note:

All the other quickstart guides result in the launch of website.
This change would result in a link displayed in the terminal.

For consistency, I would prefer to see the quickstart guide end with `ddev launch`. Followed by a comment below that shares the `ddev drush uli` tip.

2024-01-25 08:59 UTC, stasadev requested changes
@tyler36 I agree with standardization.

@Nick-Hope, maybe it can be written like this:

```
# use the one-time link (CTRL/CMD + Click) from the command below to edit your admin account details.
ddev drush uli
ddev launch
```

2024-01-26 13:55 UTC, Nick-Hope commented
A number of approaches here would be acceptable. Decided the @stasadev suggestion was as good as any.

2024-01-26 18:32 UTC, stasadev approved these changes

2024-01-26 19:55 UTC, merged