docs: adds second snippet to Multiple Docroots in nginx
ddev/ddev pull request #5761
Opened 2024-02-01 02:05 UTC by bmartinez287

Added notes from Andy Blum on issue #4854

2024-02-01 02:09 UTC, bmartinez287 commented on docs/content/users/extend/customization-extendibility.md
> +.ddev/nginx_full/randomnamesecond.conf
```suggestion
.ddev/nginx_full/first-random-name.conf
```

2024-02-01 02:10 UTC, bmartinez287 commented on docs/content/users/extend/customization-extendibility.md
> +.ddev/nginx_full/randomname.conf
```suggestion
.ddev/nginx_full/original-random-name.conf
```

2024-02-02 13:29 UTC, rfay requested changes
Thanks for capturing this. There are still some problems with the docs check, https://github.com/ddev/ddev/actions/runs/7735247282/job/21090580613?pr=5761 etc.

2024-02-02 13:29 UTC, rfay commented on docs/content/users/extend/customization-extendibility.md
> +#### First snippet
Please use a descriptive title instead of "First" and "Second". 

```suggestion
#### Example Nginx Snippet: Redirecting http to https
```

2024-02-02 13:29 UTC, rfay commented on docs/content/users/extend/customization-extendibility.md
> +#### Second snippet
```suggestion
#### Example Nginx Snippet: Using Node.JS Server as Back-End
```

2024-02-02 13:59 UTC, rfay commented
Still some textlint trouble, see https://github.com/ddev/ddev/pull/5761/files/606796bfec681a469df552b9b83c7d65a352e1fd..d12d5c6b11ba7a722c6fb4119d736ba6cea9d3a6

2024-02-02 14:16 UTC, rfay requested changes
Ooops, unfortunately your new node.js one is not a snippet, it's an example of using nginx_full. Could you please move it? Snippets are really quite different.

2024-02-02 14:19 UTC, bmartinez287 commented
Sure, where do examples like this could go? Any preference?

2024-02-02 14:31 UTC, rfay commented
The underlying problem is that there isn't good distinction in that docs page between snippets (.ddev/nginx) and full config (.ddev/nginx_full). 

At one time I tried to remove the snippet feature and people screamed :)  Maybe the docs got confused.

If you wouldn't mind trying to add the difference into your PR it would be appreciated. 

* "Multiple Docroots" is an example of nginx_full (where the whole nginx config is replaced)
* The HTTP redirect is an example of a snippet
* Yours is an example of nginx_full, so the very least would be to turn multiple docroots and yours into nginx_full examples.
* the idea of "snippet" is never explained, needs to be explained (where the snippet is placed into the config)

Sorry to have you stumble on this weakness, would love it if you could sort it out.

2024-02-02 20:34 UTC, rfay commented
Sorry to have you discovering that problem. I'll be happy to take it up if you don't want to. Seems some docs must have been lost somewhere along the way.

2024-02-02 20:46 UTC, bmartinez287 commented
I think I got most everything but explaining the snippets. That I'm not so sure.

2024-02-02 20:59 UTC, rfay commented
Snippets (that go in .ddev/nginx) are included in the last line of the nginx-site.conf:
```
    include /mnt/ddev_config/nginx/*.conf;
```

https://github.com/ddev/ddev/blob/c9d8f544333e7d8f4692280279169df5f228fdcc/pkg/ddevapp/webserver_config_assets/nginx-site-php.conf#L70

That means that they can do anything they want in the `server` stanza, but can't do anything outside the `server` context.

nginx_full, of course, is the complete contents of nginx-site.conf, which can actually contain more than `server`

2024-02-02 21:41 UTC, bmartinez287 commented
I rephrased it a little, but I will between that and the full example right below it it provides a clear picture. 
I could have done the nginx custom config for ddev.com ddev config after looking and Andy example.
Without it there are too many unknowns.

2024-02-03 23:00 UTC, rfay commented
I just realized that this probably actually belongs in https://ddev.readthedocs.io/en/latest/users/extend/customization-extendibility/#using-nodejs-with-ddev instead of in the nginx section (but the nginx section to refer to it)

2024-02-05 15:50 UTC, rfay commented
I'm spending a little time with this.

2024-02-05 20:57 UTC, rfay commented
I know tremendously little about the node.js ecosystem. But I assume there are websites entirely implemented in node.js, which could then be used with an nginx front-end and node.js back-end. That's essentially what you're doing here, but you're putting multiple back-ends in there and leaving the php-fpm back-end in use.

2024-02-26 18:28 UTC, rfay commented
I think this ends up being too complex for the regular docs. Would you consider doing this as an article in ddev.com, or Stack Overflow?

I do think we can improve what we have currently, and I also agree that we should capture @andy-blum 's work, but I think this PR is going to be too much.

2024-02-26 18:33 UTC, bmartinez287 commented
Sounds good

2024-02-26 18:34 UTC, closed without merging

2024-03-01 18:26 UTC, andy-blum commented
@bmartinez287 I started a blog post for my own site based on that same comment. Feel free to use it/modify it/etc

https://github.com/andy-blum/andy-blum/pull/8/files