docs: find all DDEV binaries using `which -a ddev`
ddev/ddev pull request #5834
Opened 2024-02-13 20:50 UTC by stasadev

## The Issue

Multiple `ddev` can be in a `PATH`.
And the older `ddev` may have a higher priority, so users wonder why their `ddev` is not "updating".

## How This PR Solves The Issue

Adds the `which -a ddev` technique in several places in the documentation. My priority is that when you type `old ddev` in the search, it will be shown.
Uses `which -a ddev` in `ddev self-upgrade`.

## Manual Testing Instructions

Run `ddev self-upgrade` with one `ddev` in `PATH`, repeat with multiple `ddev` in `PATH`.

## Automated Testing Overview

## Related Issue Link(s)

## Release/Deployment Notes

2024-02-13 21:10 UTC, rfay requested changes
Fantastic, thanks. Minor suggestions.

2024-02-13 21:10 UTC, rfay commented on docs/content/users/usage/faq.md
> +You can check each binary version by its full path (`/usr/bin/ddev version`) to find old versions. Remove them preferably in the same way you installed them, i.e. `/home/linuxbrew/.linuxbrew/bin/ddev
```suggestion
You can check each binary version by its full path (`/usr/bin/ddev version`) to find old versions. Remove them preferably in the same way you installed them, i.e. `/home/linuxbrew/.linuxbrew/bin/ddev` should be removed with Homebrew: `brew uninstall ddev`.
```

2024-02-13 21:10 UTC, rfay commented on docs/content/users/usage/troubleshooting.md
> +## `ddev version` Shows the old version
```suggestion
## `ddev --version` shows an old version
```

`ddev --version` is slightly preferable because there's less noise going on.

2024-02-13 21:10 UTC, rfay commented on docs/content/users/usage/troubleshooting.md
> +If you have installed the latest version of DDEV, and when you check the actual version with `ddev version`, it shows an older version, please refer to [Why do I have an old DDEV?](./faq.md#why-do-i-
```suggestion
If you have installed the latest version of DDEV, but when you check the actual version with `ddev --version`, it shows an older version, please refer to [Why do I have an old DDEV?](./faq.md#why-do-i-have-an-old-ddev)
```

2024-02-13 21:13 UTC, stasadev commented on docs/content/users/usage/faq.md
> +You can check each binary version by its full path (`/usr/bin/ddev version`) to find old versions. Remove them preferably in the same way you installed them, i.e. `/home/linuxbrew/.linuxbrew/bin/ddev
```suggestion
You can check each binary version by its full path (`/usr/bin/ddev --version`) to find old versions. Remove them preferably in the same way you installed them, i.e. `/home/linuxbrew/.linuxbrew/bin/ddev` should be removed with Homebrew.
```

2024-02-13 21:22 UTC, rfay commented on docs/content/users/usage/faq.md
> +You can check each binary version by its full path (`/usr/bin/ddev version`) to find old versions. Remove them preferably in the same way you installed them, i.e. `/home/linuxbrew/.linuxbrew/bin/ddev
Thanks

2024-02-14 00:11 UTC, tyler36 commented
Thats's great! I didn't know about `-a` .

2024-02-14 03:38 UTC, merged