fix: ddev start should not continue if web/db containers aren't healthy
ddev/ddev pull request #5871
Opened 2024-02-19 16:43 UTC by rfay

## The Issue

On a number of [rancher desktop tests](https://buildkite.com/ddev/macos-rancher-desktop/builds/586#018dc0d5-43b7-4b9d-87ee-30c8d521908b) we're seeing docker having failed, and DDEV having detected startup failure, but continuing on in processing app.Start(), eventually seeing the misleading "Something is wrong with Docker or Colima and /mnt/ddev_config is not mounted from the project .ddev folder. This can cause all kinds of problems."
 
We also saw this misleading output on 
* https://github.com/ddev/ddev-sqlsrv/issues/20

## How This PR Solves The Issue

If the web and db containers can't come up, stop the app.Start() and error out.

## Manual Testing Instructions

## Automated Testing Overview

## Related Issue Link(s)

## Release/Deployment Notes

2024-02-19 19:54 UTC, stasadev requested changes

2024-02-19 19:54 UTC, stasadev commented on pkg/ddevapp/ddevapp.go
> +		util.Failed("Failed waiting for web/db containers to become ready: %v", err)
```suggestion
		util.Failed("Failed waiting for web/db containers to become ready: %v", waitErr)
```

2024-02-19 20:03 UTC, rfay commented on pkg/ddevapp/ddevapp.go
> +		util.Failed("Failed waiting for web/db containers to become ready: %v", err)
Great eye, thanks.

2024-02-19 20:04 UTC, stasadev approved these changes

2024-02-20 05:25 UTC, GuySartorelli approved these changes
Great idea!

2024-02-21 13:55 UTC, merged