feat: add ddev ssh --cwd option, fixes #5839
ddev/ddev pull request #5894
Opened 2024-02-25 02:59 UTC by diegoe

## The Issue
* https://github.com/ddev/ddev/issues/5839

## How This PR Solves The Issue
Implements a `--cwd` option into `ddev ssh` so that you are logged into the equivalent directory _inside_ the guest.

## Manual Testing Instructions
1. Go to a `ddev` project
2. Browse into children directory under the `docroot`
3. `ddev ssh --cwd`
4. You should now be in the equivalent directory _inside_ the guest

## Automated Testing Overview

A test was hastily coded but I couldn't figure out how to test locally without downloading a million CMSs

## Release/Deployment Notes
* `ddev ssh` is now able to log you into the `web` container's equivalent directory to the host's current working directory. For example, if on the host your current working directory is `your-app/your-docroot/themes/custom/your-theme` and you call `ddev ssh --cwd` you will be logged into the guest under `/var/www/html/docroot/themes/custom/your-theme`. This option only works for `web` containers and is mutually exclusive with `--dir`.

2024-02-25 03:47 UTC, diegoe commented
I'm not super enthusiastic about the name of the option, but I guess that's the clearest way of saying "you'll go to whatever $CWD is equivalent of inside the guest"? Needless to say that I have no clue about Go, and this is largely "context clues inspired hacking" :)

2024-02-25 20:21 UTC, rfay commented
Rebased to get current testing setup

2024-03-05 18:41 UTC, stasadev requested changes
> I'm not super enthusiastic about the name of the option, but I guess that's the clearest way of saying "you'll go to whatever $CWD is equivalent of inside the guest"?

@diegoe, you meant `$PWD`, not `$CWD`, right?

I found that `cwd` is used as a config option in VSCode (but it can be hard to guess what it is on the first try).

---

This works fine with the default working dir

```
ddev config --web-working-dir /var/www/html
```

But not with something else like

```
ddev config --web-working-dir /var/www/html/test
```

2024-03-05 22:18 UTC, rfay commented
I think you might be happier (and everybody else too) with just having a global custom web command `sshhere`:
```
#!/bin/bash

#ddev-generated
## Description: Equivalent of 'ssh' but execs into same directory as on host
## Usage: sshhere 
## Example: "ddev sshhere"
## ExecRaw: true
## HostWorkingDir: true

bash 
```

Put that in ~/.ddev/commands/web/sshhere and `ddev restart` and then use `ddev sshhere`, for example:

```
rfay@rfay-tag1-m1:~/workspace/d10/web/sites/default$ ddev sshhere
rfay@d10-web:/var/www/html/web/sites/default$
```

2024-03-05 22:27 UTC, diegoe commented
> > I'm not super enthusiastic about the name of the option, but I guess that's the clearest way of saying "you'll go to whatever $CWD is equivalent of inside the guest"?
> 
> @diegoe, you meant `$PWD`, not `$CWD`, right?
> 
> I found that `cwd` is used as a config option in VSCode (it can be hard to guess what it is on the first try) - but I'm okay with this naming.

For this specific context the two terms would be interchangeable. I'm personally used to `cwd`, whether in APIs or shell, because of PHP and Python, that use `getcwd()` and `os.getcwd()` in their standard libraries.

> This works fine with the default working dir
> 
> ```
> ddev config --web-working-dir /var/www/html
> ```
> 
> But not with something else like
> 
> ```
> ddev config --web-working-dir /var/www/html/test
> ```

Oh, I wasn't familiar with that option. Perhaps it should match explicitly to the `docroot`? In that case, the option could explain itself to be limited to equivalents _inside_ the `docroot` only (?), which I believe is the most useful aspect of this.

Perhaps the counter argument to making it more flexible, like allowing anything under `working_dir` (now that I know the option) or `$HOME` or all of the above, is that it would make it unpredictable (?). I have limited familiarity with more complex `ddev` use cases so I might be ignoring obvious conflicts, or opportunities, here.

Can you suggest what would be a preferred, or more predictable, criteria? My intuition is to choose the behavior that is the most predictable, less surprising, to the user (`docroot` only?). But again I'm limited to very simple use cases (`ddev start` of whatever was provided to me), so I might be overlooking something obvious.

Thanks!

2024-03-05 22:32 UTC, rfay commented
`ddev ssh` once used to land in the docroot, but then things like doing `composer install` don't typically work in the docroot. Etc. That's why it lands in the project root.

2024-03-05 22:32 UTC, diegoe commented
> Put that in ~/.ddev/commands/web/sshhere and `ddev restart` and then use `ddev sshhere`, for example:

This works perfectly for what I need. Thanks 👍 

Feel free to close this PR and issue if you don't see it fitting into the command itself.

2024-03-05 22:42 UTC, rfay commented
We have a number of commands like `ssh` and `exec` and `share` that predate shell-based commands... and would be better reimplemented the other way.

2024-03-06 14:43 UTC, rfay commented
Thanks for your work on this and for taking the time to create a contribution PR. I hope you'll do it again!  (Next time, please do an issue before you invest in a lot of work in the PR so you can make sure the conversation gets done before you do the work. Although most of the time it's not this much work.)

Since this adds complexity and there's already a `ddev ssh -d` option, and since you have a good workaround, I think I'm going to go ahead and close it. 

It still would have needed updates to docs, and the `cwd` vs `pwd` conversation would have been confusing in the long term. (Note that golang uses `os.Getwd()` to skip the whole conversation :) )

2024-03-06 14:43 UTC, closed without merging