feat: Improve container errors messages format, fix #6042
ddev/ddev pull request #6043
Opened 2024-04-02 16:39 UTC by penyaskito

## The Issue

TBD

## How This PR Solves The Issue

TBD

## Manual Testing Instructions

TBD

## Automated Testing Overview

TBD

## Related Issue Link(s)

## Release/Deployment Notes

2024-04-02 17:00 UTC, stasadev requested changes
Thanks! You can also replace all `please use %s to find out why it failed` with `more info with %s` to show all the suggested commands at the end of the sentence.

2024-04-02 17:12 UTC, stasadev commented
Rebased to resolve conficts.

2024-04-03 11:08 UTC, stasadev approved these changes
Thanks, tested an `unhealthy` container using #6033 as a base, with changes from this PR:

```
Failed waiting for web/db containers to become ready: web container failed: log=&{2024-04-03 14:05:33.767050037 +0300 EEST 2024-04-03 14:05:34.569456346 +0300 EEST 143 php-fpm:FATAL Shut down
}, err=ddev-d10-web container is unhealthy: &{2024-04-03 14:05:33.767050037 +0300 EEST 2024-04-03 14:05:34.569456346 +0300 EEST 143 php-fpm:FATAL Shut down
}, more info with [
        ddev logs -s web
        docker logs ddev-d10-web
        docker inspect --format "{{ json .State.Health }}" ddev-d10-web
]
```

2024-04-04 17:45 UTC, rfay commented
@penyaskito @stasadev please make sure you're OK with it. I just wanted to make sure it went in today for our v1.23.0-beta1 release.

2024-04-04 17:49 UTC, stasadev approved these changes
Nice addition, thanks!
Tested it and got pretty formatted output.

2024-04-04 18:01 UTC, penyaskito commented
Can't test this atm but LGTM. Thanks Randy!

2024-04-04 19:13 UTC, merged

2024-04-04 19:14 UTC, rfay commented
Yay, congrats @penyaskito !