fix: clear omit_containers config with empty flag, fixes #6140
ddev/ddev pull request #6202
Opened 2024-05-17 08:48 UTC by jonesrussell

## Issue

`ddev config --omit-containers=""` doesn't remove `omit_containers` from `.ddev/config.yaml` as expected (#6140).

## Solution

This PR clears `omit-containers` when an empty string is passed. It uses the `Changed` method, consistent with the global version of the command. Changes are made in `handleMainConfigArgs` in `cmd/ddev/cmd/config.go`.

## Testing

Manual testing involves running `ddev config --omit-containers=db` and `ddev config --omit-containers=""` and checking `.ddev/config.yaml`. Automated tests will be added to verify the flag's functionality.

## Related Issues

Fixes issue #6140.

## Deployment

No special deployment actions needed. This change doesn't affect other code.

2024-05-17 13:21 UTC, rfay commented
Thanks for this! Could you please evaluate the `ddev config global --omit-containers` situation also, and poke around just a bit to see if we have other commands that deal with arrays that aren't clear-able?

2024-05-31 23:23 UTC, rfay commented
Rebased, looking forward to your work on this.

2024-06-06 01:48 UTC, rfay commented
Hoping you can take a look, it would be good to get these things taken care of together. Thanks!

2024-06-06 01:49 UTC, rfay commented
Rebased.

2024-07-09 11:58 UTC, stasadev commented
Another flag with the same problem: `additional_fqdns`

2024-07-09 12:25 UTC, spoonerWeb commented
> Another flag with the same problem: `additional_fqdns`

And `additional_hostnames`

2024-07-16 14:57 UTC, jonesrussell commented
The global flag is already removing omit_containers as expected.

I added checks for additional-hostnames and additional-fqdns.

There was code duplication, so I added a `processFlag` function.

2024-07-16 14:59 UTC, rfay commented
You're awesome, thanks!

2024-07-16 15:13 UTC, rfay commented
Pushed a commit to pacify golangci-lint, the `else` was redundant there, https://github.com/ddev/ddev/pull/6202/commits/d0ad534e6d51a1f9f4d8ba795624dc099ec7095a

You can precheck this with `make staticrequired`

2024-07-16 15:24 UTC, jonesrussell commented
Ah thanks for the linter check heads up.

After looking at processFlag again I thought it reads better if we return early when flag is not changed.

2024-07-18 00:35 UTC, rfay commented
I started looking at this and found that there were a few other array-type arguments, then added test coverage and found that we were failing. There are some things that definitely work under bash (where quotes get processed automatically) and don't work in some other contexts.

* Added other items
* Added project test coverage
* Added global items
* Added global test coverage

And of course I discovered that we should have been using the `StringSlice` type in Cobra (like we do for `upload-dirs`) for all of these, and our life would have been so much easier. I tried converting some of these to StringSlice, but it ended up being a little risky and likely to change the existing behavior.

https://github.com/ddev/ddev/blob/f6977639ad2ee95667352ccb527371881abe8954/cmd/ddev/cmd/config.go#L233

Now it needs a whole new review and manual testing, including testing of all the affected array types.

2024-07-18 19:31 UTC, stasadev approved these changes
Looks good to me.

2024-07-18 19:38 UTC, stasadev requested changes

2024-07-18 19:38 UTC, stasadev commented on cmd/ddev/cmd/config_test.go
> +	assert.Empty(app.WebEnvironment)
```suggestion
	assert.Empty(app.AdditionalHostnames)
	assert.Empty(app.AdditionalFQDNs)
	assert.Empty(app.DBImageExtraPackages)
	assert.Empty(app.OmitContainers)
	assert.Empty(app.UploadDirs)
	assert.Empty(app.WebEnvironment)
	assert.Empty(app.WebImageExtraPackages)
```

2024-07-18 19:38 UTC, stasadev commented on cmd/ddev/cmd/config_test.go
> +		out, err := exec.RunHostCommand(DdevBin, "delete", "-Oy", strings.ToLower(t.Name()))
```suggestion
		out, err := exec.RunHostCommand(DdevBin, "delete", "-Oy", projectName)
```

2024-07-18 19:38 UTC, stasadev commented on docs/content/users/usage/commands.md
> +* `--additional-fqdns`: Comma-delimited list of project FQDNs or `--additional-fqdns=""` to remoe any configured FQDNs.
```suggestion
* `--additional-fqdns`: Comma-delimited list of project FQDNs or `--additional-fqdns=""` to remove any configured FQDNs.
```

2024-07-18 19:38 UTC, stasadev commented on docs/content/users/usage/commands.md
> +* `--omit-containers`: For example, `--omit-containers=ddev-ssh-agent` or `--omit-containers=""".
```suggestion
* `--omit-containers`: For example, `--omit-containers=ddev-ssh-agent` or `--omit-containers=""`.
```

2024-07-18 20:02 UTC, stasadev approved these changes

2024-07-19 15:18 UTC, merged

2024-07-19 15:18 UTC, rfay commented
Thanks @jonesrussell !