fix: run `pre_install_actions` add-on actions in `.ddev` folder
ddev/ddev pull request #6447
Opened 2024-07-30 11:53 UTC by stasadev

## The Issue

While working on

- https://github.com/ddev/ddev-varnish/pull/28

I noticed that different add-on actions are performed in different contexts, which is confusing.

- `pre_install_actions` in `$DDEV_APPROOT`
- `post_install_actions` in `$DDEV_APPROOT/.ddev`
- `removal_actions` in `$DDEV_APPROOT/.ddev`

## How This PR Solves The Issue

Changes the running directory for `pre_install_actions` from `$DDEV_APPROOT` to `$DDEV_APPROOT/.ddev`

It will break things for these official add-ons (which can be fixed later):

- https://github.com/ddev/ddev-mongo/blob/main/install.yaml
- https://github.com/ddev/ddev-sqlsrv/blob/main/install.yaml

## Manual Testing Instructions

```
mkdir miniaddon && echo "name: miniaddon\npre_install_actions:\n- pwd\npost_install_actions:\n- pwd\nremoval_actions:\n- pwd" > miniaddon/install.yaml
# the output should show .ddev folder everywhere
ddev get miniaddon
ddev get --remove miniaddon
```

## Automated Testing Overview

## Release/Deployment Notes

It can break `pre_install_actions` for some unofficial add-ons:

@rfay suggested: we can manually run https://github.com/ddev/ddev-add-on-monitoring against all add-ons for a while after this goes in, and before release.

The fix would be pretty easy, use `$DDEV_APPROOT` inside `pre_install_actions` in `install.yaml`:

```diff
-touch .ddev/some-file
+touch $DDEV_APPROOT/.ddev/some-file
```

2024-07-30 11:55 UTC, stasadev commented
This PR normalizes the running context for everything except `yaml_read_files` which runs in `$DDEV_APPROOT`, I wonder if we should change it to `$DDEV_APPROOT/.ddev`

2024-07-30 13:15 UTC, rfay commented
> I wonder if we should change it to $DDEV_APPROOT/.ddev

Agreed that we should. It's not unlikely that ddev -platformsh is the only user. 

IMO it's quite naive that it doesn't already use $DDEV_APPROOT to explicitly name the directory.

https://github.com/ddev/ddev-platformsh/blob/bb7365e30ae68797602dd0f648bf16bb46cd62b3/install.yaml#L330-L333

2024-07-30 14:09 UTC, rfay commented
Looks like TestCmdGet has some problems. Not sure why I see those only on macOS.

2024-07-30 16:11 UTC, rfay requested changes
This looks good to me. As you suggested, we should
* do yaml_read_files as well
* Update the ddev-addon-template (including explicitly using $DDEV_APPROOT in there)
* Fix ddev-platformsh proactively
* Carefully run the monitoring script after this goes in and fix what it breaks.

2024-07-30 16:25 UTC, rfay commented
* https://github.com/ddev/ddev-platformsh/pull/126

2024-07-30 16:48 UTC, rfay commented
`yaml_read_files` already puts together the full path, so adding ${DDEV_APPROOT} on the front of those files ends up with 
> /Users/rfay/tmp/test-platformsh/Users/rfay/tmp/test-platformsh/.platform.app.yaml: unable to read file /Users/rfay/tmp/test-platformsh/Users/rfay/tmp/test-platformsh/.platform.app.yaml (open /Users/rfay/tmp/test-platformsh/Users/rfay/tmp/test-platformsh/.platform.app.yaml: no such file or directory)

2024-07-30 16:57 UTC, rfay commented
I guess maybe `yaml_read_files` code should check to see if path is rooted?

2024-07-30 17:17 UTC, stasadev commented
Yes, it can be done in a similar way to:

https://github.com/ddev/ddev/blob/c2aca52a18687e678086dd232573cf51914dba56/cmd/ddev/cmd/auth-ssh.go#L40-L45

2024-07-30 17:37 UTC, rfay commented
This also makes `ddev get` on relative directories fail.

For example, 

`ddev get ../ddev-platformsh` fails
`ddev get ${PWD}/../ddev-platformsh` succeeds

2024-07-30 18:27 UTC, stasadev commented
It might be better to leave everything as is, but change the docs properly with `ddev-addon-template` as they are incorrect:

https://ddev.readthedocs.io/en/latest/users/extend/additional-services/#sections-and-features-of-ddev-get-add-on-installyaml

2024-07-30 19:10 UTC, rfay commented
Shucks. Well, we tried!

2024-07-30 19:18 UTC, stasadev commented
Related change:

- https://github.com/ddev/ddev-addon-template/pull/54

2024-08-01 22:26 UTC, rfay approved these changes
Thanks!

2024-08-01 22:27 UTC, merged