feat: automatic timezone detection (except traditional Windows), fixes #6458
ddev/ddev pull request #6468
Opened 2024-08-07 09:49 UTC by stasadev

## The Issue

- #6458

## How This PR Solves The Issue

We can use the `/etc/localtime` symlink to get the timezone from the host.
As far as I can tell, this doesn't work on traditional Windows where `/etc/localtime` does not exist.

## Manual Testing Instructions

Unset timezone if it is set:
```
ddev config --timezone=""
```

Run
```
DDEV_DEBUG=true ddev start
...
2024-08-07T12:41:13.739 Using automatically detected timezone: TZ=Europe/Kyiv
...
```
Check the timezone inside the container:
```
ddev exec 'echo $TZ'
ddev exec date
ddev php -r "var_dump(date_default_timezone_get());"
```

Retry `ddev start` after changing the time zone on the host to check for a different timezone.

## Automated Testing Overview

## Release/Deployment Notes

2024-08-07 11:51 UTC, stasadev commented
I see two problems here, which may or may not be important:

1. If a new timezone has been added to the host, but the `tzdata` inside the `web` or `db` images does not have it (an example of how it was with `Europe/Kyiv` https://stackoverflow.com/a/78156172/8097891), `UTC` will be used as a fallback time, but `date` will show the wrong thing for timezone.

    This can be fixed if we inject update for `tzdata`.

2. If you use some old database image (where `tzdata` cannot be updated) and your timezone is set to something new, it will show the wrong thing in the `db` container.

	For example, `Europe/Kyiv` was added recently, and it will not work with old `postgres` image:
	
	```
	ddev config --database="postgres:9" --dbimage-extra-packages=tzdata
	ddev start
	
	ddev exec -s db 'echo $TZ'
	Europe/Kyiv

	ddev exec -s db "date && TZ=UTC date" # it uses UTC time, but shows Europe
	Wed Aug  7 11:41:14 Europe 2024
	Wed Aug  7 11:41:14 UTC 2024
	
	ddev exec -s db date +%Z
	Europe
	```

	AFAICT, there is no easy fix for this old `tzdata`.

---

TODO (after successful tests):

1. Think about injecting `tzdata` update
2. remove optional `right/` and `posix/` from the timezone symlink https://stackoverflow.com/q/67885319/8097891

2024-08-07 14:36 UTC, stasadev commented
> Here's a complete list of results for Windows

Thanks, I also saw this `tzutil /g` utility and it gives you a result, which cannot be converted to the exact timezone used by the user in the IANA format.

I don't think I can add and maintain all possible timezones for Windows, it's too much of a burden considering we only have ~6.54% of users using traditional Windows:

<details>
  <summary>Amplitude statistics</summary>
  <img src="https://github.com/user-attachments/assets/d6da469d-84ab-48f8-a768-acfbbbadc966"></img>
</details>

2024-08-07 14:51 UTC, stasadev commented
> devblogs.microsoft.com/oldnewthing/20210527-00?p=105255

> If you run it with two command line parameters, then we treat the first as the Windows time zone and the second as the region, and convert the pair to an IANA time zone.

I also need a region code (where to get it?)

---

Another answer from SO, that I found: https://stackoverflow.com/a/63860078/8097891

And from that here is a full list of Windows timezones https://github.com/unicode-org/cldr/blob/main/common/supplemental/windowsZones.xml

So I need not only `tzutil /g` but also the region code, and even after that I can't tell which is the exact timezone the user is using because it returns multiple results.

But this is, of course, some progress 🙂

2024-08-08 13:04 UTC, rfay requested changes
This works great. I tested manually on gitpod (Linux), WSL2, Windows, macOS. It didn't break anything on Windows, worked great everywhere else. 

It doesn't respect TZ of course, I guess it doesn't have to. It could. 

The only thing is a discussion about whether we could read the link and process it using golang techniques instead of shelling out.

2024-08-08 13:15 UTC, stasadev commented on pkg/ddevapp/ddevapp.go
> +	timezone, err := exec.RunHostCommand(bash, "-c", "[ ! -e /etc/localtime ] || /usr/bin/readlink -f /etc/localtime 2>/dev/null || /bin/readlink -f /etc/localtime 2>/dev/null")
Wow, you're absolutely right, I think I used Bash only because it was easy to test.

2024-08-08 13:45 UTC, stasadev commented
> It doesn't respect `TZ` of course, I guess it doesn't have to. It could.

Good idea. `TZ` support will make it easier with traditional Windows, we won't need some workarounds with running PowerShell or whatever.

2024-08-08 15:09 UTC, rfay commented
I think for TZ it can just be added to app_compose_template.yaml with no value in the environment section.

2024-08-23 05:42 UTC, stasadev commented
I added TZ env, it will work with this priority:

1. `app.Timezone`
2. `$TZ`
3. `readlink -f /etc/localtime`
4. `UTC`

2024-08-23 08:01 UTC, tyler36 commented
Tested on WSL Ubuntu (on Win11) and works expected.

## Test

1. Confirm DDEV version

    ```shell
    $ ddev -v
    ddev version v1.23.4-10-g44c57f46b
    ```

1. Check web container

    ```shell
    $  ddev . date
    Fri Aug 23 16:51:23 JST 2024
    $ ddev -s web . date
    Fri Aug 23 16:51:48 JST 2024
    ```

1. Check db container

    ```shell
    $ ddev -s db . date 
    Fri Aug 23 16:51:59 JST 2024
    ```


1. Confirm WSL system time

    ```shell
    $ echo $TZ 
    
    ```

    No value appears set. Try more detailed check.

    ```shell
    $ timedatectl
                   Local time: Fri 2024-08-23 16:54:06 JST
               Universal time: Fri 2024-08-23 07:54:06 UTC
                     RTC time: Fri 2024-08-23 07:54:06
                    Time zone: Asia/Tokyo (JST, +0900)
    System clock synchronized: yes
                  NTP service: inactive
              RTC in local TZ: no
    ```

2024-08-23 10:41 UTC, rfay approved these changes
It's good! 

This will change behavior for a large number of people, so we have to get it into the release notes. I doubt that anybody who really cares will stumble on it, because they will already have `timezone` set in config.yaml

2024-08-23 10:41 UTC, merged