Add back the command to renew LE certs.
ddev/ddev pull request #6469
Opened 2024-08-07 13:46 UTC by jonpugh

## The Issue

- #TBD

The documentation for casual hosting was missing instructions for renewing letsencrypt certificates. I googled it and turns out Google cached the old docs?

> You'll need to regularly renew the Let's Encrypt certificates. This is often done on a system reboot, but that may not be soon enough. A cron with the command docker exec ddev-router bash -c "certbot renew && nginx -s reload" will do the renewals.

## How This PR Solves The Issue

Adds this paragraph to the letsencrypt notes.

2024-08-07 13:56 UTC, rfay requested changes
This is no longer required, as traefik does the work.

2024-08-07 14:04 UTC, jonpugh commented
Ah that explains it. 

I can't remember why, but I needed to use `nginx-proxy` for my ddev site runner thing. 

I'm using it for production for www.thinkdrop.net!

2024-08-07 14:05 UTC, rfay commented
Have you set up the new traefik technique? I haven't yet done it on my little server.

2024-08-07 14:08 UTC, rfay commented
BTW, misspelling Persistant -> Persistent

Interested in hearing more about Operations Site Runner. Are you interested in doing a guest blog on ddev.com?

2024-08-14 20:16 UTC, rfay commented
The suggested commands won't work with traefik router and shouldn't be needed any more. We'll see!

2024-08-14 20:16 UTC, closed without merging