fix: always show `pv` output on `ddev import-db`
ddev/ddev pull request #6484
Opened 2024-08-14 13:03 UTC by stasadev

## The Issue

- https://github.com/orgs/ddev/discussions/6483

Users cannot redirect `pv` output on `ddev import-db`

To reproduce:

```
ddev exec "pv /dev/zero | head -c 5M | while read -r line; do sleep 0.01; done" >stdout.txt 2>stderr.txt
```
And view inside `stderr.txt`

## How This PR Solves The Issue

Uses `pv -f` instead of `pv`

```
$ pv -h
Usage: pv [OPTION] [FILE]...
Concatenate FILE(s), or standard input, to standard output, with monitoring.
...
  -f, --force                    output even if standard error is not a terminal
...
```

## Manual Testing Instructions

```
ddev exec "pv -f /dev/zero | head -c 5M | while read -r line; do sleep 0.01; done" >stdout.txt 2>stderr.txt
```
And view inside `stderr.txt`

Or
```
ddev import-db --file=db.sql.gz >stdout.txt 2>stderr.txt
```
And view inside `stderr.txt`

## Automated Testing Overview

## Release/Deployment Notes

2024-08-14 14:35 UTC, Mathijs-Zuiderlicht commented
I ran your manual testing instructions in Gitpod: ddev import-db --file=db.sql.gz >stdout.txt 2>stderr.txt
Here's the contents of stderr.txt

```
 896KiB 0:00:01 [ 818KiB/s] [<=>                                               ]
1.50MiB 0:00:02 [ 676KiB/s] [ <=>                                              ]
2.25MiB 0:00:03 [ 698KiB/s] [  <=>                                             ]
2.88MiB 0:00:04 [ 691KiB/s] [   <=>                                            ]
3.62MiB 0:00:05 [ 683KiB/s] [    <=>                                           ]
4.25MiB 0:00:06 [ 678KiB/s] [     <=>                                          ]
4.88MiB 0:00:07 [ 698KiB/s] [      <=>                                         ]
5.00MiB 0:00:07 [ 698KiB/s] [       <=>                                        ]
```

Looks alright to me. 
I tried your test command on my machine without your changes and got an empty stderr.txt.

2024-08-14 15:28 UTC, rfay reviewed
I was afraid that this might break importing from stdin, but it seems to be fine.

2024-08-14 15:28 UTC, stasadev commented
@Mathijs-Zuiderlicht,

I just tried this in Gitpod:

```
ddev export-db --file=db.sql.gz
ddev import-db --file=db.sql.gz >stdout.txt 2>stderr.txt
```
stderr.txt:
```
9.03MiB 0:00:01 [8.98MiB/s] [========================>         ] 76% ETA 0:00:00
11.7MiB 0:00:01 [7.35MiB/s] [================================>] 100%            
```

---

```
ddev export-db --file=db.sql --gzip=false
ddev import-db --file=db.sql >stdout.txt 2>stderr.txt
```
stderr.txt:
```
9.03MiB 0:00:01 [8.84MiB/s] [========================>         ] 76% ETA 0:00:00
11.7MiB 0:00:01 [7.27MiB/s] [================================>] 100%        
```

2024-08-17 12:28 UTC, rfay requested changes
What this PR does is to force output even if stderr is not a terminal. From `pv -h`:

>   -f, --force              output even if standard error is not a terminal

The purpose of (not) forcing is to not display things in a non-interactive environment that don't belong there. For example, the test instructions given here that redirect `2>/stderr.txt`. The reality is that we really wouldn't want those to happen most of the time.

The simple answer for the OP in https://github.com/orgs/ddev/discussions/6483 is to change your node process to pretend to be a terminal. I'm not sure that's possible, but that's the easy answer. The reason that pv isn't showing output is that the stderr isn't a terminal. 

I'm open to conversation, but changing working code to unexpected code for a very unusual situation seems like it may be the wrong thing, and the OP code could possibly adapt instead.

2024-08-19 19:10 UTC, stasadev commented
> Could this break any existing automated tests that use `ddev import-db` ?

I think this change to `stderr` may have an impact if someone's code checks the output in `stderr`.

And we can't redirect the output of `pv` to `stdout` because that would completely override it.

2024-08-19 19:41 UTC, rfay commented
I think it may be OK, just wonder if the experimental node code could just act like a terminal and that would solve the problem.

2024-08-19 19:43 UTC, rfay commented
There may be some answers in https://stackoverflow.com/questions/68344362/how-do-i-get-full-visual-control-of-a-terminal-with-node

In general, the answer would probably be "behave like a terminal in order to get code like pv to think you're a terminal"

2024-08-20 13:21 UTC, Mathijs-Zuiderlicht commented
I ended up doing something like this:
`const importCommand = 'wsl -d Ubuntu pv -f ' + dumpFilePath + ' | wsl -d Ubuntu --cd ' + appRoot + ' ddev mysql -uroot -proot ' + myDB`
instead of: 
`const importCommand = 'wsl -d Ubuntu --cd ' + appRoot + ' ddev import-db --file=${dumpFileName}';`

It works perfectly for my use case. This also doesn't require any changes in DDEV ;)

@rfay and @stasadev thank you for looking into it.

2024-08-22 17:03 UTC, stasadev commented
Closing this.

A workaround is to pipe the `ddev import-db` command to `pv` as shown above.

2024-08-22 17:03 UTC, closed without merging