docs: remove import/export 'redirect operator' examples
ddev/ddev pull request #6584
Opened 2024-10-04 01:52 UTC by cooperka

### Reason for change

Neither of these examples works reliably, and they should not be recommended to the average user.

### Example of export issue

See #6583.

### Example of import issue

Using `ddev import-db < ../db.sql.gz` (note that the file is gzipped) drops the database and then fails with something like:

```
grep: (standard input): binary file matches
Error: failed to import database 'db' for project: failed to import database: composeCmd failed to run 'COMPOSE_PROJECT_NAME=ddev-project docker-compose -f /Users/cooperka/project/.ddev/.ddev-docker-compose-full.yaml exec -T db bash -c set -eu -o pipefail && mysql -uroot -proot -e "DROP DATABASE IF EXISTS db; CREATE DATABASE IF NOT EXISTS db; GRANT ALL ON db.* TO 'db'@'%';"  2> >(grep -v 'Deprecated program name.' >&2)  && perl -p -e 's/^(CREATE DATABASE \/\*|USE `)[^;]*;//' | mysql db  2> >(grep -v 'Deprecated program name.' >&2) ', action='[exec -T db bash -c set -eu -o pipefail && mysql -uroot -proot -e "DROP DATABASE IF EXISTS db; CREATE DATABASE IF NOT EXISTS db; GRANT ALL ON db.* TO 'db'@'%';"  2> >(grep -v 'Deprecated program name.' >&2)  && perl -p -e 's/^(CREATE DATABASE \/\*|USE `)[^;]*;//' | mysql db  2> >(grep -v 'Deprecated program name.' >&2) ]', err='exit status 1', stdout='', stderr='grep: (standard input): binary file matches'
stdout:
stderr: grep: (standard input): binary file matches
```

It's not clear in the docs that the redirect operator ONLY works for uncompressed files, unlike every other example which works for both compressed and uncompressed files.

2024-10-04 01:58 UTC, rfay commented
The redirect operator works fine for compressed tings.

`ddev export-db >junk.sql.gz` works and creates a perfect file, if nothing else is going on (like starting DDEV)

2024-10-04 15:33 UTC, cooperka commented
I agree it works if nothing else is going on, but can we make the assumption that the average user knows that a prerequisite for this command to work reliably is that "nothing else is going on"? That seems risky, and in my case caused a full day of redoing work after my backups turned out to be unusable.

I did confirm by the way that additional stdout logs (including blank lines) corrupted the MIDDLE of the gzipped binary file, so it was very difficult to fix. In some cases you can simply remove the first few lines of stdout to fix the backup, but not always.

I don't think the docs should recommend a command that may silently fail to produce a valid backup. If you disagree, feel free to close.

2024-10-04 17:34 UTC, stasadev commented
Let's simply add `ddev start &&` to these commands with redirect:

```diff
-ddev export-db > /tmp/db.sql.gz
+ddev start && ddev export-db > /tmp/db.sql.gz
```

This works fine.

And we need update here:

https://github.com/ddev/ddev/blob/cccd95557898033d74c83bedea1b608ac6651345/cmd/ddev/cmd/export-db.go#L22-L23

And here:

https://github.com/ddev/ddev/blob/cccd95557898033d74c83bedea1b608ac6651345/cmd/ddev/cmd/import-db.go#L41-L43

Don't forget about pipe:

```diff
-gzip -dc db.sql.gz | ddev import-db
+ddev start && gzip -dc db.sql.gz | ddev import-db
```

Thank you.

2024-10-04 19:50 UTC, cooperka commented
Thanks for the suggestion @stasadev. I can make a change across those files too.

Just to clarify, ddev does not need to be running to import (it will start automatically). The issue with import is that it doesn't accept gzipped files with a redirect operator.

So, since the redirect operator is universally worse than just using the `--file=` argument, I'd still argue we should simply avoid recommending the redirect operator. It's less useful for both import and export. It's not an equivalent option and should not be documented as such. We could add all this context to explain how and when it works, but it's so much easier to just remove.

2024-10-04 19:57 UTC, rfay commented
You're right that `ddev import-db` expects plain-vanilla text as input, as most other utilities do. 

For example:
```
$ gzip -dc .tarballs/db.sql.gz | ddev import-db
mysql: [Warning] Using a password on the command line interface can be insecure.
Successfully imported database 'db' for d11
```

2024-10-04 19:58 UTC, rfay commented
I agree that it's odd that `ddev export-db` has always output gzipped content by default. It was one of those things that was like that very early and was hard to change after that.

2024-10-04 20:33 UTC, cooperka commented
I'm having a difficult time working with you @rfay, your comments are reading as defensive to me and I'm just trying to help. Could you please be explicit about what action item you're looking for? More feedback from others perhaps, or a specific change from me?

2024-10-04 20:55 UTC, rfay commented
I'm very much appreciating your proactive response to the friction you encountered! I'm trying to explain the history and the possible paths to improving the docs. That's why I suggested the `gzip -dc <db.sql.gz | ddev import-db` approach. Since you like pipes (and I like them very much) I thought you might want to include that.

2024-10-05 20:13 UTC, rfay commented
And a follow-up: Thanks for being open about feeling like it's difficult working with me. I think most people would walk away instead of saying that, and it's a marvelous thing that you know how to continue the conversation. If you'd like to see if we can take the edge off with a call about this (or anything else), let's talk at https://cal.com/randyfay/30min

2024-10-08 20:24 UTC, rfay requested changes
The items that are removed in this PR all work correctly. I'm certainly open to more examples.

2024-10-08 22:22 UTC, cooperka commented
Like I said, I don't think the docs should recommend a command that may silently fail to produce a valid backup. If you disagree, feel free to close.

2024-10-10 15:21 UTC, rfay commented
Closing, as this removes valid examples. Improvement to the examples and addition of new ones will be welcome.

2024-10-10 15:21 UTC, closed without merging