docs: rearrange documentation on making PRs
ddev/ddev pull request #6676
Opened 2024-11-03 22:02 UTC by joachim-n

## The Issue

I can never find the PR docs because they're hiding in a page that says it's about setting up a local build and running tests, and in that page the information about PRs is split over different parts.

## How This PR Solves The Issue

- makes the link say the page is also about making PRs.
- consolidates and reorganises the bits about making PRs

## Manual Testing Instructions

## Automated Testing Overview

## Release/Deployment Notes

2024-11-04 00:50 UTC, rfay requested changes
Looks like a nice improvement to me, thanks. Minor suggestions.

2024-11-04 21:06 UTC, joachim-n commented on docs/content/developers/building-contributing.md
> +If your pull request is merged, great! If not, no sweat; it may not be what the project maintainer had in mind, or they were already working on it. This happens, so our recommendation is to take any
I've not changed any of that paragraph, just moved it around. Removing it feels out of scope for what I was trying to fix here.

2024-11-04 22:56 UTC, rfay commented on docs/content/developers/building-contributing.md
> +If your pull request is merged, great! If not, no sweat; it may not be what the project maintainer had in mind, or they were already working on it. This happens, so our recommendation is to take any
When you muck with stuff that should be mucked with, things get spread around :) You're welcome to ignore.

2024-11-05 08:50 UTC, joachim-n commented on docs/content/developers/building-contributing.md
> +If your pull request is merged, great! If not, no sweat; it may not be what the project maintainer had in mind, or they were already working on it. This happens, so our recommendation is to take any
It's obvious to people who are familiar with open source, which to be fair will probably be most people who are using DDEV in the first place. But I think that having it conveys a welcoming culture of contribution, so it does add something.

2024-11-05 08:51 UTC, joachim-n commented
@rfay Committed you rewording suggestion and made a further change. This is ready again.

2024-11-06 14:59 UTC, rfay approved these changes
Works for me, thanks.

2024-11-08 03:36 UTC, merged