docs: describe how to create empty database
ddev/ddev pull request #6848
Opened 2024-12-21 12:32 UTC by gitressa

## The Issue

Sometimes, you need an empty database, for later usage. Maybe an install process requires a database present, but you don't want to import a huge database first, just for the install process to over-write it, and then import the big database again.

It is possible to create an empty database manually, as can be seen in [How can I create and load a second database in ddev?](https://stackoverflow.com/questions/49785023/how-can-i-create-and-load-a-second-database-in-ddev/49785024#49785024)

However it requires a few steps, and simply importing an empty text file is much easier.

**Future**: Maybe, in the future, the `ddev import-db` command could get a `--create-db` option, something like this?

```
ddev import-db --database=other_db --create-db
```

## How This PR Solves The Issue

## Manual Testing Instructions

## Automated Testing Overview

## Release/Deployment Notes

2024-12-21 14:21 UTC, rfay requested changes

2024-12-21 14:21 UTC, rfay commented on docs/content/users/usage/database-management.md
> +To create an empty, extra database for later usage, create an empty file with `touch dummy_db.sql` and import it with `ddev import-db --database=civicrm_db --file=dummy_db.sql`. This creates an empty
My preference to create an empty database would be the way you'd do it anywhere in the mysql/mariadb world:

```
ddev mysql -uroot -proot -e 'CREATE DATABASE newdatabase; GRANT ALL on newdatabase.* to "db"@"%";'
```

As this section makes clear, you can do anything with the db server that you would do on a server. And this could be put in a hook (perhaps with `IF NOT EXISTS newdatabase`

I think I'd propose two paths here:

1. Put your solution the SQL solution in a Stack Overflow question/answer or
2. Start a new section of database query examples.

We can't teach everybody the basics of everything or they get lost in the details.

2024-12-21 14:58 UTC, gitressa commented on docs/content/users/usage/database-management.md
> +To create an empty, extra database for later usage, create an empty file with `touch dummy_db.sql` and import it with `ddev import-db --database=civicrm_db --file=dummy_db.sql`. This creates an empty
Thanks for fast and great feedback @rfay, I really appreciate it. I would prefer option number 2, so that the documentation is housed here in the DDEV docs, and have updated the MR, What do you think?

2024-12-27 17:34 UTC, rfay commented
See if you like it here @gitressa

2024-12-27 18:46 UTC, gitressa commented
That looks great, thanks @rfay!

Though, I found something ... `ddev mariadb` doesn't seem to work, but `ddev mysql` does:

```
$ ddev mariadb
Error: unknown command "mariadb" for "ddev"
Run 'ddev --help' for usage.
$ ddev mysql
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 21
[...]
```

It's also not in the list:

```
$ ddev
Create and maintain a local web development environment.
Docs: https://ddev.readthedocs.io
Support: https://ddev.readthedocs.io/en/stable/users/support/

Usage:
  ddev [command]

Available Commands:
  add-on           A collection of commands for managing installed 3rd party add-ons
  aliases          Shows all aliases for each command in the current context (global or project).
  auth             A collection of authentication commands
  blackfire        Enable or disable blackfire.io profiling (global shell web container command)
  cake             Run cake CLI inside the web container (global shell web container command)
  clean            Removes items DDEV has created
  completion       Generate the autocompletion script for the specified shell
  composer         Executes a Composer command within the web container
  config           Create or modify a DDEV project configuration in the current directory
  craft            Run Craft CMS command inside the web container (global shell web container command)
  debug            A collection of debugging commands
  delete           Remove all project information (including database) for an existing project
  describe         Get a detailed description of a running DDEV project.
  dotenv           Commands for managing the contents of .env files
  exec             Execute a shell command in the container for a service. Uses the web service by default.
  export-db        Dump a database to a file or to stdout
  help             Help about any command
  hostname         Manage your hostfile entries.
  import-db        Import a SQL dump file into the project
  import-files     Pull the uploaded files directory of an existing project to the default public upload directory of your project
  launch           Launch a browser with the current site (global shell host container command)
  list             List projects
  logs             Get the logs from your running services.
  mailpit          Launch a browser with Mailpit (an email & SMTP testing tool) (global shell host container command)
  mutagen          Commands for Mutagen status and sync, etc.
  mysql            run mysql client in db container (global shell db container command)
  npm              Run npm inside the web container (global shell web container command)
  nvm              Run nvm inside the web container (global shell web container command)
  php              Run php inside the web container (global shell web container command)
  phpmyadmin       Prompt downloading phpMyAdmin if it is not installed. (global shell host container command)
  poweroff         Completely stop all projects and containers
  pull             Pull files and database using a configured provider plugin.
  push             push files and database using a configured provider plugin.
  restart          Restart a project or several projects.
  self-upgrade     Explain how to upgrade DDEV (global shell host container command)
  share            Share project on the internet via ngrok.
  snapshot         Create a database snapshot for one or more projects.
  ssh              Starts a shell session in the container for a service. Uses web service by default.
  start            Start a DDEV project.
  stop             Stop and remove the containers of a project. Does not lose or harm anything unless you add --remove-data.
  version          Print DDEV version and component versions
  xdebug           Enable or disable xdebug (global shell web container command)
  xhprof           Enable or disable xhprof (global shell web container command)
  yarn             Run yarn inside the web container in the root of the project (Use --cwd for another directory) (global shell web container command)

Flags:
  -h, --help          help for ddev
  -j, --json-output   If true, user-oriented output will be in JSON format.
      --skip-hooks    If true, any hook normally run by the command will be skipped.
  -v, --version       version for ddev

Use "ddev [command] --help" for more information about a command.
```

2024-12-27 18:54 UTC, rfay commented
`ddev mariadb` is being introduced in 
* https://github.com/ddev/ddev/pull/6851

I figured we might as well mention it.

2024-12-27 21:04 UTC, gitressa commented
Thanks for clarifying. I looked around and saw that [MariaDB was bought by the K1 private equity group](https://techcrunch.com/2024/09/10/mariadb-goes-private-with-new-ceo-as-k1-closes-acquisition/) earlier this year, which could explain the recent changes, and separation from the MySQL brand ...

2024-12-27 21:06 UTC, gitressa reviewed
It still says "change requested" even though I thought I approved the change.

2024-12-27 23:29 UTC, merged

2024-12-28 11:39 UTC, gitressa commented
Thanks!