feat: disable `ddev config` in the project's parent dir, fixes #6783
ddev/ddev pull request #6852
Opened 2024-12-23 15:43 UTC by stasadev

## The Issue

- #6783

## How This PR Solves The Issue

Automatically disable `ddev config` in the project's parent directory when you run `ddev config` in the project's dir.

I decided to add only one flag `--no-config-here` for simplicity.

TODO:

- [ ] Check if we can allow `ddev config` in the project subdirectory.

## Manual Testing Instructions

```
ddev config --auto
cd ..

ddev config
could not create new config: 'ddev config' is not allowed in the /home/stas/workspace directory, use 'ddev config global --no-config-here=false' if you want to allow it

ddev config global --no-config-here=false

ddev config # should work, but don't create a project here, stop with ^C

ddev config global --no-config-here

ddev config
could not create new config: 'ddev config' is not allowed in the /home/stas/workspace directory, use 'ddev config global --no-config-here=false' if you want to allow it
```

## Automated Testing Overview

## Release/Deployment Notes

2024-12-23 15:46 UTC, rfay reviewed
Of course this doesn't prevent them from doing it wrong the first time. (`ddev config` in ~/workspace for example)

2024-12-26 23:36 UTC, gitressa commented
Thanks @stasadev, the PR will also solve this issue:
- #5493

2024-12-27 15:39 UTC, rfay reviewed
I tried the simplest case of what I think this is supposed to prevent and it allowed me to do it. I keep my projects in ~/workspace, and I did a `ddev config` or `ddev config --auto` there and it allowed it.

2024-12-27 15:46 UTC, stasadev commented
`ddev config` is supposed to be run at the project level at least once to add the exclusion.

So, first run `ddev config --auto` in the project directory `~/workspace/project`, and then go to the parent directory.

2024-12-27 15:48 UTC, stasadev commented
I think I can make it better by reading `project_list.yaml` instead of relying on `ddev config`. Thank you for testing.

2025-01-03 18:15 UTC, stasadev commented
After reconsidering, I decided to disable `ddev config` in any parent directory of the project.

This is the simplest approach and should prevent confusion, except when `ddev config` is run in the wrong place initially, which we can't fully prevent.

At the same time, I allowed `ddev config` in the project subdirectories. I will see how the tests go.

2025-01-06 14:49 UTC, rfay commented
> could not create new config: 'ddev config' is not allowed in the /Users/rkoller/testung directory because it has a project in the subdirectory /Users/rkoller/testung/subdir/drupal
> To use 'ddev config' here, please 'ddev delete' the project in the subdirectory first

I haven't looked yet, but wouldn't one need to both `ddev delete` or `ddev stop --unlist` *and* remove the offending .ddev/config.yaml?

2025-01-06 15:09 UTC, rpkoller commented
> I haven't looked yet, but wouldn't one need to both `ddev delete` or `ddev stop --unlist` _and_ remove the offending .ddev/config.yaml?

delete does that, it stops the running project (if not running it starts it to be able to create a snapshot if you dont add --omit-snapshot,) and then removes it from the list of known project.

2025-01-06 15:39 UTC, stasadev commented
> Would it be possible to start the message upper case?

I'll take a look. It is written with a lowercase only because of `golangci-lint`.

> i wonder why to add a path to subdirectory? would it be enough to simply tell" there is a ddev project in a subdirectory" without providing an absolute path?

This subdirectory can be many levels deeper, so I think it's best to tell the user the exact location.

> and on second thought it is also sort of misleading, "To use 'ddev config' here, please 'ddev delete' the project in the subdirectory first" is referring to just a single project and saying deleting that project in the subdirectory will enable you to run ddev config in the given directory. but in my case that wouldnt be possible cuz after deleting the first project the next would be listed?

I wanted to give the user general instructions, but we can definitely improve it. Let's brainstorm a better message.

> and would it make sense to go with "recommended" instead of "useful"?

Yes, easy to change, thanks.

2025-01-06 15:49 UTC, rpkoller commented
out of curiosity one question first before going into brainstorming mode, is ddev aware how many projects are blockers and also knows all their paths?

2025-01-06 15:51 UTC, stasadev commented
> is ddev aware how many projects are blockers and also knows all their paths?

Yes, we have that information (we just need to count it), I used an early return to keep it simple without checking the number of projects.

2025-01-07 16:37 UTC, rfay requested changes
* `ddev config` in a subdirectory does in fact reconfig the parent directory project, but it inappropriately messes up the message about docroot creation,  (it actually doesn't create the docroot web/web or put that into the config.yaml):

```
$ ddev config --webserver-type=apache-fpm
You are reconfiguring the project at /home/rfay/workspace/d11.
The existing configuration will be updated and replaced.
Configuring a 'drupal11' project named 'd11' with docroot 'web' at '/home/rfay/workspace/d11/web/web'.
For full details use 'ddev describe'.
Configuration complete. You may now run 'ddev start'.
```
* One thing we may want to keep in mind for people is they don't actually need to use `ddev config` and can use manual creation of a .ddev/config.yaml to work around these restrictions if necessary.
* Is there anything we need to do in docs? I doubt it. But there may be some support events that get triggered by this and can probably be fixed with manual config.yaml creation.

2025-01-07 16:37 UTC, rfay commented on cmd/ddev/cmd/config.go
> +	err = ddevapp.IsAllowedProjectLocation(app)
Nice refactoring.

2025-01-07 16:37 UTC, rfay commented on cmd/ddev/cmd/config_test.go
> +	// Make sure that 'ddev config' in a subdir doesn't give an error for existing project
TestCmdDisasterConfig needs a better name (and comment). OK to rename. It was built around the homedir failure of course, and now it's covering more ground.

2025-01-07 16:37 UTC, rfay commented on pkg/ddevapp/config.go
> +	if app.AppRoot == filepath.Dir(globalconfig.GetGlobalDdevDir()) || app.AppRoot == homeDir {
Can we expand this to parents of homedir? I haven't heard of it happening, but what if people accidentally did /home or /Users ?

2025-01-07 16:37 UTC, rfay commented on pkg/ddevapp/config.go
> +	for _, project := range projectList {
This is a good and adequate strategy, although I have accidentally created projects that have a .ddev in a subdirectory. It's typically when I have done something like a `ddev stop --unlist -a`, removing everything from global project list, or when my global config has been damaged somehow.

2025-01-07 16:37 UTC, rfay commented on pkg/ddevapp/config.go
> +			return fmt.Errorf("'ddev config' is not allowed in the %s directory because it has a project in the subdirectory %s\nTo use 'ddev config' here, please 'ddev delete' the project in the subdirectory
`ddev delete` is not really required, and does more than expected. `ddev stop --unlist` ? Or should we just always assume that delete is the best answer?

2025-01-07 16:48 UTC, stasadev commented on pkg/ddevapp/config.go
> +	if app.AppRoot == filepath.Dir(globalconfig.GetGlobalDdevDir()) || app.AppRoot == homeDir {
Yes, we can.

2025-01-07 16:50 UTC, stasadev commented on pkg/ddevapp/config.go
> +			return fmt.Errorf("'ddev config' is not allowed in the %s directory because it has a project in the subdirectory %s\nTo use 'ddev config' here, please 'ddev delete' the project in the subdirectory
I don't know yet, I will think about it.

2025-01-07 16:50 UTC, stasadev commented
> `ddev config` in a subdirectory does in fact reconfig the parent directory project, but it inappropriately messes up the message about docroot creation

Thanks, I'll take a look.

> One thing we may want to keep in mind for people is they don't actually need to use `ddev config` and can use manual creation of a .ddev/config.yaml to work around these restrictions if necessary.

I agree, if they want to do it, then it's their choice.

> Is there anything we need to do in docs? I doubt it. But there may be some support events that get triggered by this and can probably be fixed with manual config.yaml creation.

I don't know how people develop Drupal, but can they have Drupal modules that are DDEV projects inside other DDEV projects?

2025-01-07 16:59 UTC, rfay commented
> I don't know how people develop Drupal, but can they have Drupal modules that are DDEV projects inside other DDEV projects?

That's a good question. The best practice right now is https://github.com/ddev/ddev-drupal-contrib, which I think just does the project it the top directory. There is also https://github.com/joachim-n/drupal-project-contrib-development

But I don't think either one would explicitly use `ddev config`, which is the thing we're working with here.

2025-01-07 17:01 UTC, rfay commented
The ability to safely use `ddev config` in a subdirectory and have it config the right thing is a huge improvement to DDEV, thank you!

2025-01-08 17:37 UTC, stasadev commented
I implemented all the suggestions and slightly rephrased the error message.
Additionally, I added everything under `~/.ddev` to the exclusion list.

2025-01-08 22:46 UTC, rfay approved these changes
It's awesome, and such an excellent improvement, in both directions. `ddev config` in a subdirectory of valid project works *fine* instead of messing up. And `ddev config` in parent directory balks. And it was great that you disabled inside .ddev directory.

2025-01-09 00:02 UTC, rpkoller reviewed
the changes are mostly about changing recommended to allowed after a brief discussion with @rfay and he recommended going with allowed which is the most precise in that context. aside that i did only two minor nitpicks . one change from plural to singular for directory and one rephrasing of a sentence open for discussion. aside that i hope i haven missed a recommend nor was too overeager. and functionwise the PR is still in excellent shape, thank you for all the excellent work!

2025-01-09 11:53 UTC, stasadev commented
Thanks @rpkoller, much better now!

I read the related issues and added one more check for `ddev/ddev` repository root. (I run `ddev config` here too 😅)

> * https://github.com/ddev/ddev/issues/5493#issuecomment-1791131045

2025-01-09 14:05 UTC, rfay commented
That is so great that you caught the "doing it in ddev repo" thing. Maybe it will only help you and me but it will sure help. Of course... I often do it in the pkg/ddevapp dir. But it's great.

2025-01-09 14:49 UTC, merged

2025-01-25 20:34 UTC, rfay commented
Conversation on this in https://drupal.slack.com/archives/C5TQRQZRR/p1737819544903659 - we may not be successful with this. Especially with ddev/ddev-drupal-contrib adding to top-level projects (drupal modules). Then you bring in one of those modules that has a checked-in .ddev directory, and you can no longer `ddev config` in the project that contains it.